# EuroSAT ResNet50 Kaggle Runner

This notebook runs staged ResNet50 experiments through CLI overrides.
It keeps one canonical defaults file and avoids creating extra per-run config files.

In [1]:
import os
import shutil
import subprocess
from pathlib import Path
from kaggle_secrets import UserSecretsClient

WORKING = Path('/kaggle/working')
REPO = WORKING / 'satellite-land-classification-dl'
REPOSITORY_URL = 'https://github.com/milanovicmilos/satellite-land-classification-dl.git'

if REPO.exists():
    shutil.rmtree(REPO)

user_secrets = UserSecretsClient()
token = user_secrets.get_secret('GH_TOKEN')

if not token:
    raise RuntimeError('Missing GH_TOKEN in Kaggle Secrets.')

auth_url = f'https://x-access-token:{token}@github.com/milanovicmilos/satellite-land-classification-dl.git'
subprocess.run(['git', 'clone', auth_url, REPO.as_posix()], check=True)
subprocess.run(
    ['git', '-C', REPO.as_posix(), 'remote', 'set-url', 'origin', REPOSITORY_URL],
    check=True,
)

target_branches = ['refactor/infrastructure-and-configs', 'dev', 'feature/efficientnet-optimization', 'main']
success = False

for branch in target_branches:
    checkout = subprocess.run(
        ['git', '-C', REPO.as_posix(), 'checkout', branch],
        capture_output=True,
        text=True,
    )
    if checkout.returncode == 0:
        print(f'Checked out: {branch}')
        success = True
        break

if not success:
    raise RuntimeError('Could not checkout to any target branch.')

%cd {REPO.as_posix()}

Cloning into '/kaggle/working/satellite-land-classification-dl'...

Checked out: refactor/infrastructure-and-configs
/kaggle/working/satellite-land-classification-dl

In [2]:
!python -m pip install --upgrade pip
!python -m pip install -e .

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 21.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.0.1
Obtaining file:///kaggle/working/satellite-land-classification-dl
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: torch>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (0.25.0+cu128)
Requirement already satisfied: Pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (11.3.0)
Collecting numpy>=2.2.0 (from eurosat-land-classification==0.1.0)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.5.0->eurosat-land-classification==0.1.0) (1.3.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.5.0->eurosat-land-classification==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.5.0->eurosat-land-classification==0.1.0) (3.0.3)
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 31.8 MB/s  0:00:00
Building wheels for collected packages: eurosat-land-classification
  Building editable for eurosat-land-classification (pyproject.toml) ... done
  Created wheel for eurosat-land-classification: filename=eurosat_land_classification-0.1.0-0.editable-py3-none-any.whl size=3401 sha256=20a884f85bc8059486d0fda7a33402036eb6bc5aabbdf0edd5f1f56aa71c1dd5
  Stored in directory: /tmp/pip-ephem-wheel-cache-nea4gwte/wheels/3a/51/ed/94edbae1ff9e3c632e6ce74bfe624ca59243f59877810503f8
Successfully built eurosat-land-classification
Installing collected packages: numpy, eurosat-land-classification
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [eurosat-land-classification]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.1 requires numpy<2.4,>=1.22, but you have numpy 2.4.4 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
Successfully installed eurosat-land-classification-0.1.0 numpy-2.4.4

## Dataset and Experiment Setup

The notebook keeps split policy fixed and runs staged ResNet50 experiments with CLI overrides.
Stage 2 runs resume from the Stage 1 best checkpoint and compare multiple fine-tuning variants.

In [3]:
import json
import pandas as pd

DATASET_INPUT_ROOT = Path('/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT')
assert DATASET_INPUT_ROOT.exists(), f'Missing dataset path: {DATASET_INPUT_ROOT}'

BASE_CONFIG = 'configs/experiment.defaults.json'
SPLITS_OUTPUT = '/kaggle/working/artifacts/splits'
REPORTS_ROOT = Path('/kaggle/working/artifacts/reports/resnet50')
CHECKPOINTS_ROOT = Path('/kaggle/working/checkpoints/resnet50')
SUMMARY_CSV = REPORTS_ROOT / 'resnet50_experiment_summary.csv'
HOLDOUT_CSV = REPORTS_ROOT / 'resnet50_holdout_report.csv'

for output_dir in (REPORTS_ROOT, CHECKPOINTS_ROOT):
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'

STAGE1_EXPERIMENT = {
    'run_id': 'resnet50_stage1_reference',
    'epochs': 30,
    'batch_size': 16,
    'learning_rate': 0.001,
    'early_stopping_patience': 2,
    'scheduler_patience': 1,
    'min_learning_rate': 0.000001,
    'augmentation_mode': 'flips',
    'freeze_backbone': True,
    'use_pretrained': True,
}

STAGE2_EXPERIMENTS = [
    {
        'run_id': 'resnet50_stage2_reference',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.0001,
        'early_stopping_patience': 3,
        'scheduler_patience': 1,
        'min_learning_rate': 0.0000001,
        'augmentation_mode': 'flips',
    },
    {
        'run_id': 'resnet50_stage2_low_lr',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.00005,
        'early_stopping_patience': 3,
        'scheduler_patience': 1,
        'min_learning_rate': 0.0000001,
        'augmentation_mode': 'flips',
    },
    {
        'run_id': 'resnet50_stage2_no_aug',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.0001,
        'early_stopping_patience': 3,
        'scheduler_patience': 1,
        'min_learning_rate': 0.0000001,
        'augmentation_mode': 'none',
    },
]


def run_cmd(cmd: list[str]) -> None:
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)


print('Stage 1 config:')
print(STAGE1_EXPERIMENT)
print('\nStage 2 grid:')
for experiment in STAGE2_EXPERIMENTS:
    print(experiment)

Stage 1 config:
{'run_id': 'resnet50_stage1_reference', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.001, 'early_stopping_patience': 2, 'scheduler_patience': 1, 'min_learning_rate': 1e-06, 'augmentation_mode': 'flips', 'freeze_backbone': True, 'use_pretrained': True}

Stage 2 grid:
{'run_id': 'resnet50_stage2_reference', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.0001, 'early_stopping_patience': 3, 'scheduler_patience': 1, 'min_learning_rate': 1e-07, 'augmentation_mode': 'flips'}
{'run_id': 'resnet50_stage2_low_lr', 'epochs': 30, 'batch_size': 16, 'learning_rate': 5e-05, 'early_stopping_patience': 3, 'scheduler_patience': 1, 'min_learning_rate': 1e-07, 'augmentation_mode': 'flips'}
{'run_id': 'resnet50_stage2_no_aug', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.0001, 'early_stopping_patience': 3, 'scheduler_patience': 1, 'min_learning_rate': 1e-07, 'augmentation_mode': 'none'}

## Scientific Selection Protocol and Run Name Glossary

Model selection rule in this notebook:
- Select the final ResNet50 run by validation macro F1 (`val_f1_best`) within the Stage 2 pool.
- Keep test accuracy and test macro F1 as holdout-only reporting metrics.

Run name glossary:
- `reference`: canonical setup used as a comparison anchor.
- `low_lr`: the same setup with a lower learning rate.
- `no_aug`: fine-tuning without data augmentation.
- `stage1`: frozen-backbone transfer stage.
- `stage2`: unfrozen fine-tuning stage resumed from Stage 1 checkpoint.

## Prepare Deterministic Splits (Shared for All Runs)

In [4]:
prepare_cmd = [
    'python',
    'run.py',
    '--prepare-dataset',
    '--config',
    BASE_CONFIG,
    '--defaults',
    'configs/experiment.defaults.json',
    '--splits-output',
    SPLITS_OUTPUT,
    '--dataset-root',
    DATASET_INPUT_ROOT.as_posix(),
    '--model-name',
    'resnet50',
    '--seed',
    str(SEED),
    '--train-ratio',
    '0.7',
    '--validation-ratio',
    '0.15',
    '--test-ratio',
    '0.15',
    '--stratified',
]

run_cmd(prepare_cmd)

python run.py --prepare-dataset --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name resnet50 --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified
{
  "dataset_root": "/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT",
  "seed": 42,
  "class_count": 10,
  "total_samples": 27000,
  "train_samples": 18900,
  "validation_samples": 4050,
  "test_samples": 4050,
  "artifacts": {
    "train": "/kaggle/working/artifacts/splits/train_split.json",
    "validation": "/kaggle/working/artifacts/splits/validation_split.json",
    "test": "/kaggle/working/artifacts/splits/test_split.json",
    "manifest": "/kaggle/working/artifacts/splits/split_manifest.json"
  }
}

## Stage 1 Run (Frozen Backbone)

In [5]:
stage1_report = REPORTS_ROOT / f"{STAGE1_EXPERIMENT['run_id']}.json"
stage1_ckpt_dir = CHECKPOINTS_ROOT / 'stage1'

run_cmd(
    [
        'python',
        'run.py',
        '--run-baseline',
        '--config',
        BASE_CONFIG,
        '--defaults',
        'configs/experiment.defaults.json',
        '--splits-output',
        SPLITS_OUTPUT,
        '--reports-output',
        stage1_report.as_posix(),
        '--checkpoints-output',
        stage1_ckpt_dir.as_posix(),
        '--dataset-root',
        DATASET_INPUT_ROOT.as_posix(),
        '--model-name',
        'resnet50',
        '--experiment-name',
        STAGE1_EXPERIMENT['run_id'],
        '--seed',
        str(SEED),
        '--epochs',
        str(STAGE1_EXPERIMENT['epochs']),
        '--batch-size',
        str(STAGE1_EXPERIMENT['batch_size']),
        '--learning-rate',
        str(STAGE1_EXPERIMENT['learning_rate']),
        '--early-stopping-patience',
        str(STAGE1_EXPERIMENT['early_stopping_patience']),
        '--early-stopping-min-delta',
        '0.001',
        '--scheduler-factor',
        '0.5',
        '--scheduler-patience',
        str(STAGE1_EXPERIMENT['scheduler_patience']),
        '--min-learning-rate',
        str(STAGE1_EXPERIMENT['min_learning_rate']),
        '--augmentation-mode',
        STAGE1_EXPERIMENT['augmentation_mode'],
        '--use-pretrained',
        '--freeze-backbone',
    ]
)

stage1_payload = json.loads(stage1_report.read_text(encoding='utf-8'))
stage1_payload['metrics']

python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/resnet50/resnet50_stage1_reference.json --checkpoints-output /kaggle/working/checkpoints/resnet50/stage1 --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name resnet50 --experiment-name resnet50_stage1_reference --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.001 --early-stopping-patience 2 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 1 --min-learning-rate 1e-06 --augmentation-mode flips --use-pretrained --freeze-backbone
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 158MB/s]

{
  "accuracy": 0.9279012345679012,
  "macro_f1_score": 0.9258586591027888,
  "precision": {
    "AnnualCrop": 0.9613636363636363,
    "Forest": 0.9600886917960089,
    "HerbaceousVegetation": 0.8775510204081632,
    "Highway": 0.837696335078534,
    "Industrial": 0.9394736842105263,
    "Pasture": 0.9018987341772152,
    "PermanentCrop": 0.9498525073746312,
    "Residential": 0.9881516587677726,
    "River": 0.87146529562982,
    "SeaLake": 0.9795918367346939
  },
  "recall": {
    "AnnualCrop": 0.94,
    "Forest": 0.9622222222222222,
    "HerbaceousVegetation": 0.9555555555555556,
    "Highway": 0.8533333333333334,
    "Industrial": 0.952,
    "Pasture": 0.95,
    "PermanentCrop": 0.8586666666666667,
    "Residential": 0.9266666666666666,
    "River": 0.904,
    "SeaLake": 0.96
  },
  "confusion_matrix": [
    [
      423,
      1,
      0,
      11,
      0,
      5,
      4,
      0,
      5,
      1
    ],
    [
      0,
      433,
      12,
      0,
      0,
      1,
      0,
      0,
      1,
      3
    ],
    [
      0,
      2,
      430,
      7,
      0,
      5,
      4,
      0,
      2,
      0
    ],
    [
      5,
      2,
      8,
      320,
      7,
      3,
      5,
      0,
      24,
      1
    ],
    [
      0,
      0,
      0,
      11,
      357,
      1,
      1,
      2,
      3,
      0
    ],
    [
      0,
      2,
      7,
      3,
      0,
      285,
      1,
      0,
      2,
      0
    ],
    [
      11,
      0,
      24,
      6,
      1,
      6,
      322,
      3,
      2,
      0
    ],
    [
      0,
      4,
      6,
      5,
      13,
      1,
      0,
      417,
      4,
      0
    ],
    [
      1,
      1,
      1,
      18,
      2,
      7,
      2,
      0,
      339,
      4
    ],
    [
      0,
      6,
      2,
      1,
      0,
      2,
      0,
      0,
      7,
      432
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/resnet50/resnet50_stage1_reference.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 5,
    "best_validation_loss": 0.21661850471280658,
    "best_validation_f1": 0.9291484274455989,
    "best_epoch": 3,
    "early_stopping_patience": 2,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 1,
    "min_learning_rate": 1e-06,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.32756080757432604,
        "val_loss": 0.23926894096281806,
        "val_acc": 0.9204938271604939,
        "val_f1": 0.9172598863931982,
        "lr": 0.001
      },
      {
        "epoch": 2,
        "train_loss": 0.2026708663946298,
        "val_loss": 0.23077434705111782,
        "val_acc": 0.9241975308641975,
        "val_f1": 0.9213311705114036,
        "lr": 0.001
      },
      {
        "epoch": 3,
        "train_loss": 0.17436990390753124,
        "val_loss": 0.21661850471280658,
        "val_acc": 0.931604938271605,
        "val_f1": 0.9291484274455989,
        "lr": 0.001
      },
      {
        "epoch": 4,
        "train_loss": 0.16008033131829552,
        "val_loss": 0.22860261045278052,
        "val_acc": 0.9269135802469136,
        "val_f1": 0.9241659011971979,
        "lr": 0.001
      },
      {
        "epoch": 5,
        "train_loss": 0.1510043501877679,
        "val_loss": 0.21993166010154916,
        "val_acc": 0.9323456790123457,
        "val_f1": 0.9301336147594037,
        "lr": 0.0005
      }
    ]
  }
}

{'accuracy': 0.9279012345679012,
 'macro_f1_score': 0.9258586591027888,
 'precision': {'AnnualCrop': 0.9613636363636363,
  'Forest': 0.9600886917960089,
  'HerbaceousVegetation': 0.8775510204081632,
  'Highway': 0.837696335078534,
  'Industrial': 0.9394736842105263,
  'Pasture': 0.9018987341772152,
  'PermanentCrop': 0.9498525073746312,
  'Residential': 0.9881516587677726,
  'River': 0.87146529562982,
  'SeaLake': 0.9795918367346939},
 'recall': {'AnnualCrop': 0.94,
  'Forest': 0.9622222222222222,
  'HerbaceousVegetation': 0.9555555555555556,
  'Highway': 0.8533333333333334,
  'Industrial': 0.952,
  'Pasture': 0.95,
  'PermanentCrop': 0.8586666666666667,
  'Residential': 0.9266666666666666,
  'River': 0.904,
  'SeaLake': 0.96},
 'confusion_matrix': [[423, 1, 0, 11, 0, 5, 4, 0, 5, 1],
  [0, 433, 12, 0, 0, 1, 0, 0, 1, 3],
  [0, 2, 430, 7, 0, 5, 4, 0, 2, 0],
  [5, 2, 8, 320, 7, 3, 5, 0, 24, 1],
  [0, 0, 0, 11, 357, 1, 1, 2, 3, 0],
  [0, 2, 7, 3, 0, 285, 1, 0, 2, 0],
  [11, 0, 24, 6, 1, 6, 322, 3, 2, 0],
  [0, 4, 6, 5, 13, 1, 0, 417, 4, 0],
  [1, 1, 1, 18, 2, 7, 2, 0, 339, 4],
  [0, 6, 2, 1, 0, 2, 0, 0, 7, 432]]}

## Stage 2 Grid (Unfrozen Backbone, Resume from Stage 1)

All Stage 2 runs resume from the same Stage 1 checkpoint and vary only selected fine-tuning hyperparameters.

In [6]:
stage1_resume_path = stage1_ckpt_dir / 'best_checkpoint.pt'
assert stage1_resume_path.exists(), f'Missing Stage 1 checkpoint: {stage1_resume_path}'

resnet_rows = []

stage1_metrics = stage1_payload['metrics']
stage1_state = stage1_payload['metadata']['training_state']
resnet_rows.append(
    {
        'run_id': STAGE1_EXPERIMENT['run_id'],
        'stage': 'stage1',
        'augmentation_mode': STAGE1_EXPERIMENT['augmentation_mode'],
        'learning_rate': STAGE1_EXPERIMENT['learning_rate'],
        'freeze_backbone': True,
        'epochs_requested': STAGE1_EXPERIMENT['epochs'],
        'epochs_ran': stage1_state.get('epochs_ran'),
        'val_f1_best': stage1_state.get('best_validation_f1'),
        'test_accuracy': stage1_metrics['accuracy'],
        'test_macro_f1': stage1_metrics['macro_f1_score'],
        'report_path': stage1_report.as_posix(),
        'checkpoint_path': stage1_payload['metadata'].get('checkpoint_path'),
    }
)

for experiment in STAGE2_EXPERIMENTS:
    run_id = experiment['run_id']
    stage2_report = REPORTS_ROOT / f"{run_id}.json"
    stage2_ckpt_dir = CHECKPOINTS_ROOT / run_id

    run_cmd(
        [
            'python',
            'run.py',
            '--run-baseline',
            '--config',
            BASE_CONFIG,
            '--defaults',
            'configs/experiment.defaults.json',
            '--splits-output',
            SPLITS_OUTPUT,
            '--reports-output',
            stage2_report.as_posix(),
            '--checkpoints-output',
            stage2_ckpt_dir.as_posix(),
            '--dataset-root',
            DATASET_INPUT_ROOT.as_posix(),
            '--model-name',
            'resnet50',
            '--experiment-name',
            run_id,
            '--seed',
            str(SEED),
            '--epochs',
            str(experiment['epochs']),
            '--batch-size',
            str(experiment['batch_size']),
            '--learning-rate',
            str(experiment['learning_rate']),
            '--early-stopping-patience',
            str(experiment['early_stopping_patience']),
            '--early-stopping-min-delta',
            '0.001',
            '--scheduler-factor',
            '0.5',
            '--scheduler-patience',
            str(experiment['scheduler_patience']),
            '--min-learning-rate',
            str(experiment['min_learning_rate']),
            '--augmentation-mode',
            experiment['augmentation_mode'],
            '--resume-from',
            stage1_resume_path.as_posix(),
            '--no-use-pretrained',
            '--no-freeze-backbone',
        ]
    )

    payload = json.loads(stage2_report.read_text(encoding='utf-8'))
    metrics = payload['metrics']
    training_state = payload['metadata']['training_state']

    resnet_rows.append(
        {
            'run_id': run_id,
            'stage': 'stage2',
            'augmentation_mode': experiment['augmentation_mode'],
            'learning_rate': experiment['learning_rate'],
            'freeze_backbone': False,
            'epochs_requested': experiment['epochs'],
            'epochs_ran': training_state.get('epochs_ran'),
            'val_f1_best': training_state.get('best_validation_f1'),
            'test_accuracy': metrics['accuracy'],
            'test_macro_f1': metrics['macro_f1_score'],
            'report_path': stage2_report.as_posix(),
            'checkpoint_path': payload['metadata'].get('checkpoint_path'),
        }
    )

resnet_summary = pd.DataFrame(resnet_rows).sort_values(
    by=['val_f1_best', 'test_macro_f1', 'test_accuracy'],
    ascending=False,
).reset_index(drop=True)

selection_pool = resnet_summary[resnet_summary['stage'] == 'stage2'].copy()
selection_pool = selection_pool.sort_values(
    by=['val_f1_best', 'test_macro_f1', 'test_accuracy'],
    ascending=False,
).reset_index(drop=True)

if selection_pool.empty:
    raise RuntimeError('Stage 2 selection pool is empty. At least one stage2 run is required.')

selected_run_id = selection_pool.iloc[0]['run_id']
resnet_summary['selected_for_final'] = resnet_summary['run_id'] == selected_run_id
best_stage2_row = resnet_summary.loc[resnet_summary['selected_for_final']].iloc[0]

selection_record = {
    'selection_rule': 'Select max(val_f1_best) within stage2 runs; keep test metrics for holdout reporting only.',
    'selection_metric': 'val_f1_best',
    'selection_pool': 'stage2',
    'selected_run_id': selected_run_id,
    'selected_val_f1_best': float(best_stage2_row['val_f1_best']),
    'split_seed': SEED,
    'runs_in_selection_pool': selection_pool['run_id'].tolist(),
}
selection_path = REPORTS_ROOT / 'resnet50_model_selection.json'
selection_path.write_text(json.dumps(selection_record, indent=2), encoding='utf-8')

resnet_summary.to_csv(SUMMARY_CSV, index=False)
pd.DataFrame([best_stage2_row]).to_csv(HOLDOUT_CSV, index=False)
print('Saved summary CSV:', SUMMARY_CSV)
print('Saved holdout CSV:', HOLDOUT_CSV)
print('Saved model selection manifest:', selection_path)
resnet_summary

python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/resnet50/resnet50_stage2_reference.json --checkpoints-output /kaggle/working/checkpoints/resnet50/resnet50_stage2_reference --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name resnet50 --experiment-name resnet50_stage2_reference --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.0001 --early-stopping-patience 3 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 1 --min-learning-rate 1e-07 --augmentation-mode flips --resume-from /kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone
{
  "accuracy": 0.9787654320987654,
  "macro_f1_score": 0.9784682223501147,
  "precision": {
    "AnnualCrop": 0.9754464285714286,
    "Forest": 0.9977324263038548,
    "HerbaceousVegetation": 0.9461206896551724,
    "Highway": 0.9862258953168044,
    "Industrial": 0.992,
    "Pasture": 0.9797979797979798,
    "PermanentCrop": 0.9604221635883905,
    "Residential": 0.9889624724061811,
    "River": 0.9734748010610079,
    "SeaLake": 0.9889624724061811
  },
  "recall": {
    "AnnualCrop": 0.9711111111111111,
    "Forest": 0.9777777777777777,
    "HerbaceousVegetation": 0.9755555555555555,
    "Highway": 0.9546666666666667,
    "Industrial": 0.992,
    "Pasture": 0.97,
    "PermanentCrop": 0.9706666666666667,
    "Residential": 0.9955555555555555,
    "River": 0.9786666666666667,
    "SeaLake": 0.9955555555555555
  },
  "confusion_matrix": [
    [
      437,
      0,
      2,
      0,
      0,
      1,
      7,
      0,
      1,
      2
    ],
    [
      0,
      440,
      8,
      0,
      0,
      0,
      0,
      2,
      0,
      0
    ],
    [
      0,
      0,
      439,
      0,
      0,
      3,
      5,
      0,
      1,
      2
    ],
    [
      5,
      0,
      2,
      358,
      0,
      0,
      3,
      0,
      7,
      0
    ],
    [
      0,
      0,
      0,
      1,
      372,
      0,
      0,
      2,
      0,
      0
    ],
    [
      2,
      1,
      6,
      0,
      0,
      291,
      0,
      0,
      0,
      0
    ],
    [
      3,
      0,
      6,
      0,
      0,
      2,
      364,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      2,
      0,
      0,
      448,
      0,
      0
    ],
    [
      1,
      0,
      1,
      4,
      1,
      0,
      0,
      0,
      367,
      1
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      448
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/resnet50/resnet50_stage2_reference/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/resnet50/resnet50_stage2_reference.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 9,
    "best_validation_loss": 0.06285718094971623,
    "best_validation_f1": 0.9784886187232578,
    "best_epoch": 6,
    "early_stopping_patience": 3,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.0001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 1,
    "min_learning_rate": 1e-07,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.3346745265669831,
        "val_loss": 0.10956933544827813,
        "val_acc": 0.9666666666666667,
        "val_f1": 0.9661103879561012,
        "lr": 0.0001
      },
      {
        "epoch": 2,
        "train_loss": 0.17723730326164908,
        "val_loss": 0.1024324028347353,
        "val_acc": 0.9686419753086419,
        "val_f1": 0.967999604406733,
        "lr": 0.0001
      },
      {
        "epoch": 3,
        "train_loss": 0.13113323367224825,
        "val_loss": 0.10579630270676287,
        "val_acc": 0.9664197530864198,
        "val_f1": 0.9659223515104143,
        "lr": 0.0001
      },
      {
        "epoch": 4,
        "train_loss": 0.11365919304897776,
        "val_loss": 0.10732649161905924,
        "val_acc": 0.9728395061728395,
        "val_f1": 0.972466774598848,
        "lr": 5e-05
      },
      {
        "epoch": 5,
        "train_loss": 0.08063075859372444,
        "val_loss": 0.07013192907241347,
        "val_acc": 0.9723456790123457,
        "val_f1": 0.9719153633372676,
        "lr": 5e-05
      },
      {
        "epoch": 6,
        "train_loss": 0.06262685799759445,
        "val_loss": 0.06285718094971623,
        "val_acc": 0.9790123456790123,
        "val_f1": 0.9784886187232578,
        "lr": 5e-05
      },
      {
        "epoch": 7,
        "train_loss": 0.057525612850157504,
        "val_loss": 0.062011977502587204,
        "val_acc": 0.9797530864197531,
        "val_f1": 0.9792282226330424,
        "lr": 5e-05
      },
      {
        "epoch": 8,
        "train_loss": 0.05096904070467093,
        "val_loss": 0.06186945367835148,
        "val_acc": 0.9790123456790123,
        "val_f1": 0.9782514184023319,
        "lr": 5e-05
      },
      {
        "epoch": 9,
        "train_loss": 0.04520469770646932,
        "val_loss": 0.06691135470001824,
        "val_acc": 0.9790123456790123,
        "val_f1": 0.9788254838651114,
        "lr": 5e-05
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/resnet50/resnet50_stage2_low_lr.json --checkpoints-output /kaggle/working/checkpoints/resnet50/resnet50_stage2_low_lr --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name resnet50 --experiment-name resnet50_stage2_low_lr --seed 42 --epochs 30 --batch-size 16 --learning-rate 5e-05 --early-stopping-patience 3 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 1 --min-learning-rate 1e-07 --augmentation-mode flips --resume-from /kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone
{
  "accuracy": 0.9795061728395061,
  "macro_f1_score": 0.97907776783121,
  "precision": {
    "AnnualCrop": 0.9673202614379085,
    "Forest": 0.9977728285077951,
    "HerbaceousVegetation": 0.9568034557235421,
    "Highway": 0.9782016348773842,
    "Industrial": 0.9788359788359788,
    "Pasture": 0.9932659932659933,
    "PermanentCrop": 0.9802816901408451,
    "Residential": 0.9911504424778761,
    "River": 0.9634464751958225,
    "SeaLake": 0.9910514541387024
  },
  "recall": {
    "AnnualCrop": 0.9866666666666667,
    "Forest": 0.9955555555555555,
    "HerbaceousVegetation": 0.9844444444444445,
    "Highway": 0.9573333333333334,
    "Industrial": 0.9866666666666667,
    "Pasture": 0.9833333333333333,
    "PermanentCrop": 0.928,
    "Residential": 0.9955555555555555,
    "River": 0.984,
    "SeaLake": 0.9844444444444445
  },
  "confusion_matrix": [
    [
      444,
      0,
      0,
      2,
      0,
      0,
      2,
      0,
      1,
      1
    ],
    [
      0,
      448,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    [
      1,
      0,
      443,
      1,
      0,
      1,
      3,
      0,
      1,
      0
    ],
    [
      1,
      0,
      0,
      359,
      3,
      0,
      2,
      0,
      9,
      1
    ],
    [
      0,
      0,
      0,
      2,
      370,
      0,
      0,
      3,
      0,
      0
    ],
    [
      0,
      1,
      3,
      0,
      0,
      295,
      0,
      0,
      0,
      1
    ],
    [
      8,
      0,
      14,
      1,
      1,
      1,
      348,
      1,
      1,
      0
    ],
    [
      0,
      0,
      0,
      0,
      2,
      0,
      0,
      448,
      0,
      0
    ],
    [
      1,
      0,
      0,
      2,
      2,
      0,
      0,
      0,
      369,
      1
    ],
    [
      4,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      2,
      443
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/resnet50/resnet50_stage2_low_lr/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/resnet50/resnet50_stage2_low_lr.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 11,
    "best_validation_loss": 0.06934351809766982,
    "best_validation_f1": 0.9782244012213862,
    "best_epoch": 8,
    "early_stopping_patience": 3,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 5e-05,
    "scheduler_factor": 0.5,
    "scheduler_patience": 1,
    "min_learning_rate": 1e-07,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.41431116136917673,
        "val_loss": 0.1712653557999118,
        "val_acc": 0.9520987654320988,
        "val_f1": 0.9512647826913465,
        "lr": 5e-05
      },
      {
        "epoch": 2,
        "train_loss": 0.20460203986310804,
        "val_loss": 0.20596765659293012,
        "val_acc": 0.9567901234567902,
        "val_f1": 0.9560052182756313,
        "lr": 5e-05
      },
      {
        "epoch": 3,
        "train_loss": 0.1464614760585274,
        "val_loss": 0.3809753238098828,
        "val_acc": 0.9560493827160493,
        "val_f1": 0.9555749559165101,
        "lr": 2.5e-05
      },
      {
        "epoch": 4,
        "train_loss": 0.10922108199454288,
        "val_loss": 0.5032881794146864,
        "val_acc": 0.9558024691358025,
        "val_f1": 0.9554122251272785,
        "lr": 2.5e-05
      },
      {
        "epoch": 5,
        "train_loss": 0.09628266673794138,
        "val_loss": 0.08412421906936875,
        "val_acc": 0.9701234567901235,
        "val_f1": 0.9694371043864913,
        "lr": 2.5e-05
      },
      {
        "epoch": 6,
        "train_loss": 0.07863351930125972,
        "val_loss": 0.21252213753283772,
        "val_acc": 0.9644444444444444,
        "val_f1": 0.9646957770206555,
        "lr": 2.5e-05
      },
      {
        "epoch": 7,
        "train_loss": 0.07228983693251696,
        "val_loss": 0.0849360515602905,
        "val_acc": 0.9760493827160494,
        "val_f1": 0.9758253097916876,
        "lr": 1.25e-05
      },
      {
        "epoch": 8,
        "train_loss": 0.057011313585527267,
        "val_loss": 0.06934351809766982,
        "val_acc": 0.9787654320987654,
        "val_f1": 0.9782244012213862,
        "lr": 1.25e-05
      },
      {
        "epoch": 9,
        "train_loss": 0.05250150018701756,
        "val_loss": 0.08232466075761889,
        "val_acc": 0.9782716049382716,
        "val_f1": 0.9782238112051715,
        "lr": 1.25e-05
      },
      {
        "epoch": 10,
        "train_loss": 0.04713596594553892,
        "val_loss": 0.36747556797083925,
        "val_acc": 0.9585185185185185,
        "val_f1": 0.9598458733038064,
        "lr": 6.25e-06
      },
      {
        "epoch": 11,
        "train_loss": 0.04029748405298563,
        "val_loss": 0.1605924686331219,
        "val_acc": 0.9681481481481482,
        "val_f1": 0.9686384214944216,
        "lr": 6.25e-06
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/resnet50/resnet50_stage2_no_aug.json --checkpoints-output /kaggle/working/checkpoints/resnet50/resnet50_stage2_no_aug --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name resnet50 --experiment-name resnet50_stage2_no_aug --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.0001 --early-stopping-patience 3 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 1 --min-learning-rate 1e-07 --augmentation-mode none --resume-from /kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone
{
  "accuracy": 0.9646913580246913,
  "macro_f1_score": 0.9635678984014433,
  "precision": {
    "AnnualCrop": 0.95,
    "Forest": 0.9954441913439636,
    "HerbaceousVegetation": 0.9474835886214442,
    "Highway": 0.9851632047477745,
    "Industrial": 0.9612403100775194,
    "Pasture": 0.9512987012987013,
    "PermanentCrop": 0.943089430894309,
    "Residential": 0.9954853273137697,
    "River": 0.9226932668329177,
    "SeaLake": 0.9888641425389755
  },
  "recall": {
    "AnnualCrop": 0.9711111111111111,
    "Forest": 0.9711111111111111,
    "HerbaceousVegetation": 0.9622222222222222,
    "Highway": 0.8853333333333333,
    "Industrial": 0.992,
    "Pasture": 0.9766666666666667,
    "PermanentCrop": 0.928,
    "Residential": 0.98,
    "River": 0.9866666666666667,
    "SeaLake": 0.9866666666666667
  },
  "confusion_matrix": [
    [
      437,
      0,
      1,
      1,
      0,
      5,
      3,
      0,
      2,
      1
    ],
    [
      0,
      437,
      7,
      0,
      0,
      4,
      0,
      1,
      0,
      1
    ],
    [
      1,
      2,
      433,
      1,
      0,
      1,
      12,
      0,
      0,
      0
    ],
    [
      8,
      0,
      3,
      332,
      5,
      0,
      4,
      0,
      22,
      1
    ],
    [
      0,
      0,
      0,
      1,
      372,
      0,
      1,
      1,
      0,
      0
    ],
    [
      1,
      0,
      3,
      0,
      0,
      293,
      0,
      0,
      1,
      2
    ],
    [
      10,
      0,
      10,
      0,
      0,
      5,
      348,
      0,
      2,
      0
    ],
    [
      0,
      0,
      0,
      0,
      8,
      0,
      1,
      441,
      0,
      0
    ],
    [
      1,
      0,
      0,
      2,
      2,
      0,
      0,
      0,
      370,
      0
    ],
    [
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      4,
      444
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/resnet50/resnet50_stage2_no_aug/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/resnet50/resnet50_stage2_no_aug.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 5,
    "best_validation_loss": 0.10404783709483005,
    "best_validation_f1": 0.9671767653687162,
    "best_epoch": 2,
    "early_stopping_patience": 3,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.0001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 1,
    "min_learning_rate": 1e-07,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.32386764959576375,
        "val_loss": 0.16397628716201618,
        "val_acc": 0.9469135802469136,
        "val_f1": 0.9474268826157589,
        "lr": 0.0001
      },
      {
        "epoch": 2,
        "train_loss": 0.13313399052829283,
        "val_loss": 0.10404783709483005,
        "val_acc": 0.9681481481481482,
        "val_f1": 0.9671767653687162,
        "lr": 0.0001
      },
      {
        "epoch": 3,
        "train_loss": 0.07951438407362052,
        "val_loss": 0.39303498423124245,
        "val_acc": 0.9360493827160494,
        "val_f1": 0.9381131081618165,
        "lr": 0.0001
      },
      {
        "epoch": 4,
        "train_loss": 0.0639689146539237,
        "val_loss": 0.32150813717914467,
        "val_acc": 0.948641975308642,
        "val_f1": 0.9497398943670021,
        "lr": 5e-05
      },
      {
        "epoch": 5,
        "train_loss": 0.03341482829626779,
        "val_loss": 0.15975801910429605,
        "val_acc": 0.9649382716049383,
        "val_f1": 0.9655307468243535,
        "lr": 5e-05
      }
    ]
  }
}
Saved summary CSV: /kaggle/working/artifacts/reports/resnet50/resnet50_experiment_summary.csv
Saved holdout CSV: /kaggle/working/artifacts/reports/resnet50/resnet50_holdout_report.csv
Saved model selection manifest: /kaggle/working/artifacts/reports/resnet50/resnet50_model_selection.json

,run_id,stage,augmentation_mode,learning_rate,freeze_backbone,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path,selected_for_final
0,resnet50_stage2_reference,stage2,flips,0.00010,False,30,9,0.978489,0.978765,0.978468,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,True
1,resnet50_stage2_low_lr,stage2,flips,0.00005,False,30,11,0.978224,0.979506,0.979078,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,False
2,resnet50_stage2_no_aug,stage2,none,0.00010,False,30,5,0.967177,0.964691,0.963568,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,False
3,resnet50_stage1_reference,stage1,flips,0.00100,True,30,5,0.929148,0.927901,0.925859,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/stage1/be...,False

## Final Comparison Table and Export

In [7]:
best_row = resnet_summary.loc[resnet_summary['selected_for_final']].iloc[0]
print('Best ResNet50 configuration (selected by validation macro F1 within stage2 pool):')
print(best_row[['run_id', 'stage', 'augmentation_mode', 'learning_rate', 'val_f1_best', 'test_accuracy', 'test_macro_f1']])

resnet_summary

Best ResNet50 configuration (selected by validation macro F1 within stage2 pool):
run_id               resnet50_stage2_reference
stage                                   stage2
augmentation_mode                        flips
learning_rate                           0.0001
val_f1_best                           0.978489
test_accuracy                         0.978765
test_macro_f1                         0.978468
Name: 0, dtype: object

,run_id,stage,augmentation_mode,learning_rate,freeze_backbone,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path,selected_for_final
0,resnet50_stage2_reference,stage2,flips,0.00010,False,30,9,0.978489,0.978765,0.978468,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,True
1,resnet50_stage2_low_lr,stage2,flips,0.00005,False,30,11,0.978224,0.979506,0.979078,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,False
2,resnet50_stage2_no_aug,stage2,none,0.00010,False,30,5,0.967177,0.964691,0.963568,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/resnet50_...,False
3,resnet50_stage1_reference,stage1,flips,0.00100,True,30,5,0.929148,0.927901,0.925859,/kaggle/working/artifacts/reports/resnet50/res...,/kaggle/working/checkpoints/resnet50/stage1/be...,False

In [8]:
!zip -r /kaggle/working/resnet50_results.zip /kaggle/working/artifacts /kaggle/working/checkpoints

  adding: kaggle/working/artifacts/ (stored 0%)
  adding: kaggle/working/artifacts/splits/ (stored 0%)
  adding: kaggle/working/artifacts/splits/split_manifest.json (deflated 33%)
  adding: kaggle/working/artifacts/splits/train_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/validation_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/test_split.json (deflated 98%)
  adding: kaggle/working/artifacts/reports/ (stored 0%)
  adding: kaggle/working/artifacts/reports/resnet50/ (stored 0%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_experiment_summary.csv (deflated 66%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_no_aug.json (deflated 75%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_no_aug.training_log.tmp.json (deflated 64%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_model_selection.json (deflated 50%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_low_lr.training_log.tmp.json (deflated 72%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_reference.training_log.tmp.json (deflated 71%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage1_reference.json (deflated 74%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_reference.json (deflated 76%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage2_low_lr.json (deflated 76%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_stage1_reference.training_log.tmp.json (deflated 65%)
  adding: kaggle/working/artifacts/reports/resnet50/resnet50_holdout_report.csv (deflated 43%)
  adding: kaggle/working/checkpoints/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_no_aug/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_no_aug/best_checkpoint.metadata.json (deflated 70%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_no_aug/best_checkpoint.pt (deflated 7%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_low_lr/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_low_lr/best_checkpoint.metadata.json (deflated 73%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_low_lr/best_checkpoint.pt (deflated 7%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_reference/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_reference/best_checkpoint.metadata.json (deflated 73%)
  adding: kaggle/working/checkpoints/resnet50/resnet50_stage2_reference/best_checkpoint.pt (deflated 7%)
  adding: kaggle/working/checkpoints/resnet50/stage1/ (stored 0%)
  adding: kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.metadata.json (deflated 70%)
  adding: kaggle/working/checkpoints/resnet50/stage1/best_checkpoint.pt (deflated 7%)