# EuroSAT EfficientNetB0 Kaggle Runner

This notebook runs multiple EfficientNetB0 configurations through CLI overrides.
It uses one canonical defaults file and does not rely on separate per-experiment config files.

In [1]:
import os
import shutil
import subprocess
from pathlib import Path
from kaggle_secrets import UserSecretsClient

WORKING = Path('/kaggle/working')
REPO = WORKING / 'satellite-land-classification-dl'
REPOSITORY_URL = 'https://github.com/milanovicmilos/satellite-land-classification-dl.git'

if REPO.exists():
    shutil.rmtree(REPO)

user_secrets = UserSecretsClient()
token = user_secrets.get_secret("GH_TOKEN")

if not token:
    raise RuntimeError('Missing GH_TOKEN in Kaggle Secrets.')

auth_url = f'https://x-access-token:{token}@github.com/milanovicmilos/satellite-land-classification-dl.git'
subprocess.run(['git', 'clone', auth_url, REPO.as_posix()], check=True)
subprocess.run(
    ['git', '-C', REPO.as_posix(), 'remote', 'set-url', 'origin', REPOSITORY_URL],
    check=True,
)

target_branches = ['refactor/infrastructure-and-configs' ,'dev', 'feature/efficientnet-optimization', 'main']
success = False

for branch in target_branches:
    checkout = subprocess.run(
        ['git', '-C', REPO.as_posix(), 'checkout', branch],
        capture_output=True,
        text=True,
    )
    if checkout.returncode == 0:
        print(f"Checked out: {branch}")
        success = True
        break

if not success:
    raise RuntimeError("Could not checkout to any target branch.")

%cd {REPO.as_posix()}

Cloning into '/kaggle/working/satellite-land-classification-dl'...

Checked out: refactor/infrastructure-and-configs
/kaggle/working/satellite-land-classification-dl

In [2]:
!python -m pip install --upgrade pip
!python -m pip install -e .

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 42.5 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.0.1
Obtaining file:///kaggle/working/satellite-land-classification-dl
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: torch>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (0.24.0+cu126)
Requirement already satisfied: Pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (11.3.0)
Collecting numpy>=2.2.0 (from eurosat-land-classification==0.1.0)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.5.0->eurosat-land-classification==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.5.0->eurosat-land-classification==0.1.0) (3.0.3)
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 19.9 MB/s  0:00:00
Building wheels for collected packages: eurosat-land-classification
  Building editable for eurosat-land-classification (pyproject.toml) ... done
  Created wheel for eurosat-land-classification: filename=eurosat_land_classification-0.1.0-0.editable-py3-none-any.whl size=3401 sha256=6428908f9702923315776bc417418a393bc2ba1c4ec8d2dd1dea508f406d98e8
  Stored in directory: /tmp/pip-ephem-wheel-cache-szu1r6kx/wheels/3a/51/ed/94edbae1ff9e3c632e6ce74bfe624ca59243f59877810503f8
Successfully built eurosat-land-classification
Installing collected packages: numpy, eurosat-land-classification
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [eurosat-land-classification]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.31.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.1 requires numpy<2.4,>=1.22, but you have numpy 2.4.4 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
Successfully installed eurosat-land-classification-0.1.0 numpy-2.4.4

## Dataset and Experiment Setup

The notebook keeps split policy fixed and runs staged EfficientNet experiments with CLI overrides.
Stage 2 runs resume from the Stage 1 best checkpoint and compares several logical fine-tuning variants.

In [3]:
import json
import pandas as pd

DATASET_INPUT_ROOT = Path('/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT')
assert DATASET_INPUT_ROOT.exists(), f'Missing dataset path: {DATASET_INPUT_ROOT}'

BASE_CONFIG = 'configs/experiment.defaults.json'
SPLITS_OUTPUT = '/kaggle/working/artifacts/splits'
REPORTS_ROOT = Path('/kaggle/working/artifacts/reports')
CHECKPOINTS_ROOT = Path('/kaggle/working/checkpoints/efficientnet_b0')
SUMMARY_CSV = REPORTS_ROOT / 'efficientnet_experiment_summary.csv'

REPORTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINTS_ROOT.mkdir(parents=True, exist_ok=True)

SEED = 42

STAGE1_EXPERIMENT = {
    'run_id': 'efficientnet_stage1_reference',
    'epochs': 30,
    'batch_size': 16,
    'learning_rate': 0.001,
    'early_stopping_patience': 3,
    'scheduler_patience': 2,
    'augmentation_mode': 'flips',
    'freeze_backbone': True,
    'use_pretrained': True,
}

STAGE2_EXPERIMENTS = [
    {
        'run_id': 'efficientnet_stage2_reference',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.0001,
        'early_stopping_patience': 5,
        'scheduler_patience': 3,
        'augmentation_mode': 'flips',
    },
    {
        'run_id': 'efficientnet_stage2_low_lr',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.00005,
        'early_stopping_patience': 5,
        'scheduler_patience': 3,
        'augmentation_mode': 'flips',
    },
    {
        'run_id': 'efficientnet_stage2_no_aug',
        'epochs': 30,
        'batch_size': 16,
        'learning_rate': 0.0001,
        'early_stopping_patience': 5,
        'scheduler_patience': 3,
        'augmentation_mode': 'none',
    },
]


def run_cmd(cmd: list[str]) -> None:
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)


print('Stage 1 config:')
print(STAGE1_EXPERIMENT)
print('\nStage 2 grid:')
for experiment in STAGE2_EXPERIMENTS:
    print(experiment)

Stage 1 config:
{'run_id': 'efficientnet_stage1_reference', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.001, 'early_stopping_patience': 3, 'scheduler_patience': 2, 'augmentation_mode': 'flips', 'freeze_backbone': True, 'use_pretrained': True}

Stage 2 grid:
{'run_id': 'efficientnet_stage2_reference', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.0001, 'early_stopping_patience': 5, 'scheduler_patience': 3, 'augmentation_mode': 'flips'}
{'run_id': 'efficientnet_stage2_low_lr', 'epochs': 30, 'batch_size': 16, 'learning_rate': 5e-05, 'early_stopping_patience': 5, 'scheduler_patience': 3, 'augmentation_mode': 'flips'}
{'run_id': 'efficientnet_stage2_no_aug', 'epochs': 30, 'batch_size': 16, 'learning_rate': 0.0001, 'early_stopping_patience': 5, 'scheduler_patience': 3, 'augmentation_mode': 'none'}

## Prepare Deterministic Splits (Shared for All Runs)

In [4]:
prepare_cmd = [
    'python',
    'run.py',
    '--prepare-dataset',
    '--config',
    BASE_CONFIG,
    '--defaults',
    'configs/experiment.defaults.json',
    '--splits-output',
    SPLITS_OUTPUT,
    '--dataset-root',
    DATASET_INPUT_ROOT.as_posix(),
    '--model-name',
    'efficientnet_b0',
    '--seed',
    str(SEED),
    '--train-ratio',
    '0.7',
    '--validation-ratio',
    '0.15',
    '--test-ratio',
    '0.15',
    '--stratified',
]

run_cmd(prepare_cmd)

python run.py --prepare-dataset --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name efficientnet_b0 --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified
{
  "dataset_root": "/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT",
  "seed": 42,
  "class_count": 10,
  "total_samples": 27000,
  "train_samples": 18900,
  "validation_samples": 4050,
  "test_samples": 4050,
  "artifacts": {
    "train": "/kaggle/working/artifacts/splits/train_split.json",
    "validation": "/kaggle/working/artifacts/splits/validation_split.json",
    "test": "/kaggle/working/artifacts/splits/test_split.json",
    "manifest": "/kaggle/working/artifacts/splits/split_manifest.json"
  }
}

## Stage 1 Run (Frozen Backbone)

In [5]:
stage1_report = REPORTS_ROOT / f"{STAGE1_EXPERIMENT['run_id']}.json"
stage1_ckpt_dir = CHECKPOINTS_ROOT / 'stage1'

run_cmd(
    [
        'python',
        'run.py',
        '--run-baseline',
        '--config',
        BASE_CONFIG,
        '--defaults',
        'configs/experiment.defaults.json',
        '--splits-output',
        SPLITS_OUTPUT,
        '--reports-output',
        stage1_report.as_posix(),
        '--checkpoints-output',
        stage1_ckpt_dir.as_posix(),
        '--dataset-root',
        DATASET_INPUT_ROOT.as_posix(),
        '--model-name',
        'efficientnet_b0',
        '--experiment-name',
        STAGE1_EXPERIMENT['run_id'],
        '--seed',
        str(SEED),
        '--epochs',
        str(STAGE1_EXPERIMENT['epochs']),
        '--batch-size',
        str(STAGE1_EXPERIMENT['batch_size']),
        '--learning-rate',
        str(STAGE1_EXPERIMENT['learning_rate']),
        '--early-stopping-patience',
        str(STAGE1_EXPERIMENT['early_stopping_patience']),
        '--early-stopping-min-delta',
        '0.001',
        '--scheduler-factor',
        '0.5',
        '--scheduler-patience',
        str(STAGE1_EXPERIMENT['scheduler_patience']),
        '--min-learning-rate',
        '0.000001',
        '--augmentation-mode',
        STAGE1_EXPERIMENT['augmentation_mode'],
        '--use-pretrained',
        '--freeze-backbone',
    ]
)

stage1_payload = json.loads(stage1_report.read_text(encoding='utf-8'))
stage1_payload['metrics']

python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/efficientnet_stage1_reference.json --checkpoints-output /kaggle/working/checkpoints/efficientnet_b0/stage1 --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name efficientnet_b0 --experiment-name efficientnet_stage1_reference --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.001 --early-stopping-patience 3 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 2 --min-learning-rate 0.000001 --augmentation-mode flips --use-pretrained --freeze-backbone
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 177MB/s]
/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.9261728395061728,
  "macro_f1_score": 0.9231449090117494,
  "precision": {
    "AnnualCrop": 0.9472527472527472,
    "Forest": 0.9433551198257081,
    "HerbaceousVegetation": 0.9035087719298246,
    "Highway": 0.8736263736263736,
    "Industrial": 0.9331619537275064,
    "Pasture": 0.9055374592833876,
    "PermanentCrop": 0.8898305084745762,
    "Residential": 0.9775784753363229,
    "River": 0.8826666666666667,
    "SeaLake": 0.9752808988764045
  },
  "recall": {
    "AnnualCrop": 0.9577777777777777,
    "Forest": 0.9622222222222222,
    "HerbaceousVegetation": 0.9155555555555556,
    "Highway": 0.848,
    "Industrial": 0.968,
    "Pasture": 0.9266666666666666,
    "PermanentCrop": 0.84,
    "Residential": 0.9688888888888889,
    "River": 0.8826666666666667,
    "SeaLake": 0.9644444444444444
  },
  "confusion_matrix": [
    [
      431,
      0,
      0,
      2,
      0,
      3,
      7,
      0,
      5,
      2
    ],
    [
      0,
      433,
      10,
      0,
      0,
      3,
      0,
      0,
      0,
      4
    ],
    [
      1,
      9,
      412,
      5,
      0,
      7,
      13,
      2,
      1,
      0
    ],
    [
      4,
      2,
      2,
      318,
      10,
      4,
      10,
      1,
      22,
      2
    ],
    [
      1,
      0,
      0,
      0,
      363,
      0,
      5,
      5,
      1,
      0
    ],
    [
      1,
      7,
      6,
      1,
      0,
      278,
      2,
      0,
      4,
      1
    ],
    [
      11,
      0,
      20,
      10,
      7,
      5,
      315,
      2,
      5,
      0
    ],
    [
      0,
      2,
      1,
      2,
      7,
      0,
      0,
      436,
      2,
      0
    ],
    [
      6,
      1,
      3,
      25,
      2,
      3,
      2,
      0,
      331,
      2
    ],
    [
      0,
      5,
      2,
      1,
      0,
      4,
      0,
      0,
      4,
      434
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/efficientnet_stage1_reference.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 9,
    "best_validation_loss": 0.22709523892537947,
    "best_validation_f1": 0.9207649844547323,
    "best_epoch": 6,
    "early_stopping_patience": 3,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 2,
    "min_learning_rate": 1e-06,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.5372389529196643,
        "val_loss": 0.29653707374708627,
        "val_acc": 0.9024691358024691,
        "val_f1": 0.8996662176101795,
        "lr": 0.001
      },
      {
        "epoch": 2,
        "train_loss": 0.35243215160081937,
        "val_loss": 0.26513238451590276,
        "val_acc": 0.9103703703703704,
        "val_f1": 0.9071948840834638,
        "lr": 0.001
      },
      {
        "epoch": 3,
        "train_loss": 0.3188517575235738,
        "val_loss": 0.24527514416093785,
        "val_acc": 0.9167901234567901,
        "val_f1": 0.9139417201554355,
        "lr": 0.001
      },
      {
        "epoch": 4,
        "train_loss": 0.3086112731903817,
        "val_loss": 0.23965807353635868,
        "val_acc": 0.9187654320987654,
        "val_f1": 0.9157837921364115,
        "lr": 0.001
      },
      {
        "epoch": 5,
        "train_loss": 0.3026251528528716,
        "val_loss": 0.24254473386007896,
        "val_acc": 0.9153086419753086,
        "val_f1": 0.9121061315913275,
        "lr": 0.001
      },
      {
        "epoch": 6,
        "train_loss": 0.29447175873610526,
        "val_loss": 0.22709523892537947,
        "val_acc": 0.9234567901234568,
        "val_f1": 0.9207649844547323,
        "lr": 0.001
      },
      {
        "epoch": 7,
        "train_loss": 0.28797862871412927,
        "val_loss": 0.23379467865748937,
        "val_acc": 0.9175308641975308,
        "val_f1": 0.9145641585544816,
        "lr": 0.001
      },
      {
        "epoch": 8,
        "train_loss": 0.2877827239768066,
        "val_loss": 0.228863487099884,
        "val_acc": 0.9207407407407407,
        "val_f1": 0.9179306537526806,
        "lr": 0.001
      },
      {
        "epoch": 9,
        "train_loss": 0.28313801784301573,
        "val_loss": 0.23106445639172393,
        "val_acc": 0.9162962962962963,
        "val_f1": 0.9132421499167813,
        "lr": 0.0005
      }
    ]
  }
}

{'accuracy': 0.9261728395061728,
 'macro_f1_score': 0.9231449090117494,
 'precision': {'AnnualCrop': 0.9472527472527472,
  'Forest': 0.9433551198257081,
  'HerbaceousVegetation': 0.9035087719298246,
  'Highway': 0.8736263736263736,
  'Industrial': 0.9331619537275064,
  'Pasture': 0.9055374592833876,
  'PermanentCrop': 0.8898305084745762,
  'Residential': 0.9775784753363229,
  'River': 0.8826666666666667,
  'SeaLake': 0.9752808988764045},
 'recall': {'AnnualCrop': 0.9577777777777777,
  'Forest': 0.9622222222222222,
  'HerbaceousVegetation': 0.9155555555555556,
  'Highway': 0.848,
  'Industrial': 0.968,
  'Pasture': 0.9266666666666666,
  'PermanentCrop': 0.84,
  'Residential': 0.9688888888888889,
  'River': 0.8826666666666667,
  'SeaLake': 0.9644444444444444},
 'confusion_matrix': [[431, 0, 0, 2, 0, 3, 7, 0, 5, 2],
  [0, 433, 10, 0, 0, 3, 0, 0, 0, 4],
  [1, 9, 412, 5, 0, 7, 13, 2, 1, 0],
  [4, 2, 2, 318, 10, 4, 10, 1, 22, 2],
  [1, 0, 0, 0, 363, 0, 5, 5, 1, 0],
  [1, 7, 6, 1, 0, 278, 2, 0, 4, 1],
  [11, 0, 20, 10, 7, 5, 315, 2, 5, 0],
  [0, 2, 1, 2, 7, 0, 0, 436, 2, 0],
  [6, 1, 3, 25, 2, 3, 2, 0, 331, 2],
  [0, 5, 2, 1, 0, 4, 0, 0, 4, 434]]}

## Stage 2 Grid (Unfrozen Backbone, Resume from Stage 1)

All Stage 2 runs resume from the same Stage 1 checkpoint and vary only selected fine-tuning hyperparameters.

In [6]:
stage1_resume_path = stage1_ckpt_dir / 'best_checkpoint.pt'
assert stage1_resume_path.exists(), f'Missing Stage 1 checkpoint: {stage1_resume_path}'

efficientnet_rows = []

# Include stage1 result row
stage1_metrics = stage1_payload['metrics']
stage1_state = stage1_payload['metadata']['training_state']
efficientnet_rows.append(
    {
        'run_id': STAGE1_EXPERIMENT['run_id'],
        'stage': 'stage1',
        'augmentation_mode': STAGE1_EXPERIMENT['augmentation_mode'],
        'learning_rate': STAGE1_EXPERIMENT['learning_rate'],
        'freeze_backbone': True,
        'epochs_requested': STAGE1_EXPERIMENT['epochs'],
        'epochs_ran': stage1_state.get('epochs_ran'),
        'val_f1_best': stage1_state.get('best_validation_f1'),
        'test_accuracy': stage1_metrics['accuracy'],
        'test_macro_f1': stage1_metrics['macro_f1_score'],
        'report_path': stage1_report.as_posix(),
        'checkpoint_path': stage1_payload['metadata'].get('checkpoint_path'),
    }
)

for experiment in STAGE2_EXPERIMENTS:
    run_id = experiment['run_id']
    stage2_report = REPORTS_ROOT / f"{run_id}.json"
    stage2_ckpt_dir = CHECKPOINTS_ROOT / run_id

    run_cmd(
        [
            'python',
            'run.py',
            '--run-baseline',
            '--config',
            BASE_CONFIG,
            '--defaults',
            'configs/experiment.defaults.json',
            '--splits-output',
            SPLITS_OUTPUT,
            '--reports-output',
            stage2_report.as_posix(),
            '--checkpoints-output',
            stage2_ckpt_dir.as_posix(),
            '--dataset-root',
            DATASET_INPUT_ROOT.as_posix(),
            '--model-name',
            'efficientnet_b0',
            '--experiment-name',
            run_id,
            '--seed',
            str(SEED),
            '--epochs',
            str(experiment['epochs']),
            '--batch-size',
            str(experiment['batch_size']),
            '--learning-rate',
            str(experiment['learning_rate']),
            '--early-stopping-patience',
            str(experiment['early_stopping_patience']),
            '--early-stopping-min-delta',
            '0.001',
            '--scheduler-factor',
            '0.5',
            '--scheduler-patience',
            str(experiment['scheduler_patience']),
            '--min-learning-rate',
            '0.000000001',
            '--augmentation-mode',
            experiment['augmentation_mode'],
            '--resume-from',
            stage1_resume_path.as_posix(),
            '--no-use-pretrained',
            '--no-freeze-backbone',
        ]
    )

    payload = json.loads(stage2_report.read_text(encoding='utf-8'))
    metrics = payload['metrics']
    training_state = payload['metadata']['training_state']

    efficientnet_rows.append(
        {
            'run_id': run_id,
            'stage': 'stage2',
            'augmentation_mode': experiment['augmentation_mode'],
            'learning_rate': experiment['learning_rate'],
            'freeze_backbone': False,
            'epochs_requested': experiment['epochs'],
            'epochs_ran': training_state.get('epochs_ran'),
            'val_f1_best': training_state.get('best_validation_f1'),
            'test_accuracy': metrics['accuracy'],
            'test_macro_f1': metrics['macro_f1_score'],
            'report_path': stage2_report.as_posix(),
            'checkpoint_path': payload['metadata'].get('checkpoint_path'),
        }
    )

efficientnet_summary = pd.DataFrame(efficientnet_rows).sort_values(
    by=['test_macro_f1', 'test_accuracy'],
    ascending=False,
).reset_index(drop=True)

efficientnet_summary.to_csv(SUMMARY_CSV, index=False)
print('Saved summary CSV:', SUMMARY_CSV)
efficientnet_summary

python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/efficientnet_stage2_reference.json --checkpoints-output /kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_reference --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name efficientnet_b0 --experiment-name efficientnet_stage2_reference --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.0001 --early-stopping-patience 5 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 3 --min-learning-rate 0.000000001 --augmentation-mode flips --resume-from /kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.974320987654321,
  "macro_f1_score": 0.9736213116754511,
  "precision": {
    "AnnualCrop": 0.9651416122004357,
    "Forest": 0.9977426636568849,
    "HerbaceousVegetation": 0.9481641468682506,
    "Highway": 0.9889196675900277,
    "Industrial": 0.9813829787234043,
    "Pasture": 0.9828178694158075,
    "PermanentCrop": 0.9562841530054644,
    "Residential": 0.9955056179775281,
    "River": 0.9537275064267352,
    "SeaLake": 0.975929978118162
  },
  "recall": {
    "AnnualCrop": 0.9844444444444445,
    "Forest": 0.9822222222222222,
    "HerbaceousVegetation": 0.9755555555555555,
    "Highway": 0.952,
    "Industrial": 0.984,
    "Pasture": 0.9533333333333334,
    "PermanentCrop": 0.9333333333333333,
    "Residential": 0.9844444444444445,
    "River": 0.9893333333333333,
    "SeaLake": 0.9911111111111112
  },
  "confusion_matrix": [
    [
      443,
      0,
      0,
      1,
      0,
      0,
      2,
      0,
      1,
      3
    ],
    [
      2,
      442,
      2,
      0,
      0,
      2,
      0,
      0,
      0,
      2
    ],
    [
      0,
      0,
      439,
      0,
      0,
      2,
      5,
      0,
      1,
      3
    ],
    [
      1,
      0,
      1,
      357,
      1,
      0,
      2,
      2,
      11,
      0
    ],
    [
      0,
      0,
      0,
      0,
      369,
      0,
      6,
      0,
      0,
      0
    ],
    [
      8,
      0,
      3,
      0,
      0,
      286,
      1,
      0,
      0,
      2
    ],
    [
      4,
      0,
      18,
      1,
      0,
      1,
      350,
      0,
      1,
      0
    ],
    [
      0,
      1,
      0,
      0,
      6,
      0,
      0,
      443,
      0,
      0
    ],
    [
      1,
      0,
      0,
      2,
      0,
      0,
      0,
      0,
      371,
      1
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      4,
      446
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_reference/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/efficientnet_stage2_reference.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 24,
    "best_validation_loss": 0.06011755651291701,
    "best_validation_f1": 0.9788754655532695,
    "best_epoch": 19,
    "early_stopping_patience": 5,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.0001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 3,
    "min_learning_rate": 1e-09,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 1.0199712054534498,
        "val_loss": 1.5323615616609574,
        "val_acc": 0.8676543209876543,
        "val_f1": 0.8644451504255825,
        "lr": 0.0001
      },
      {
        "epoch": 2,
        "train_loss": 0.5527828413321023,
        "val_loss": 0.7078669264923605,
        "val_acc": 0.9254320987654321,
        "val_f1": 0.9232326591191822,
        "lr": 0.0001
      },
      {
        "epoch": 3,
        "train_loss": 0.4245769639965147,
        "val_loss": 1.5191859211714243,
        "val_acc": 0.937037037037037,
        "val_f1": 0.9345548860476166,
        "lr": 0.0001
      },
      {
        "epoch": 4,
        "train_loss": 0.33819746937919504,
        "val_loss": 0.1666219612889681,
        "val_acc": 0.9461728395061728,
        "val_f1": 0.9447580876058858,
        "lr": 0.0001
      },
      {
        "epoch": 5,
        "train_loss": 0.2792221455883657,
        "val_loss": 0.1484776368771687,
        "val_acc": 0.951604938271605,
        "val_f1": 0.9498447120030529,
        "lr": 0.0001
      },
      {
        "epoch": 6,
        "train_loss": 0.23116523799878055,
        "val_loss": 0.12276426189905972,
        "val_acc": 0.9629629629629629,
        "val_f1": 0.9611124116076273,
        "lr": 0.0001
      },
      {
        "epoch": 7,
        "train_loss": 0.20653126416286666,
        "val_loss": 0.09565059556567347,
        "val_acc": 0.9676543209876544,
        "val_f1": 0.9662091252763633,
        "lr": 0.0001
      },
      {
        "epoch": 8,
        "train_loss": 0.17570222783010364,
        "val_loss": 0.1015669382440259,
        "val_acc": 0.9637037037037037,
        "val_f1": 0.9619050405999406,
        "lr": 0.0001
      },
      {
        "epoch": 9,
        "train_loss": 0.1590060756219529,
        "val_loss": 0.10552062758664059,
        "val_acc": 0.9661728395061728,
        "val_f1": 0.9647936686028753,
        "lr": 0.0001
      },
      {
        "epoch": 10,
        "train_loss": 0.1320539459445992,
        "val_loss": 0.11974353486198018,
        "val_acc": 0.9634567901234568,
        "val_f1": 0.9628284487808838,
        "lr": 0.0001
      },
      {
        "epoch": 11,
        "train_loss": 0.13138329161271176,
        "val_loss": 0.0878613027019264,
        "val_acc": 0.9708641975308642,
        "val_f1": 0.9696401199078298,
        "lr": 0.0001
      },
      {
        "epoch": 12,
        "train_loss": 0.11132728935949356,
        "val_loss": 0.08759550393722203,
        "val_acc": 0.9730864197530864,
        "val_f1": 0.9726952000844701,
        "lr": 0.0001
      },
      {
        "epoch": 13,
        "train_loss": 0.11150854360836683,
        "val_loss": 0.08002040197221848,
        "val_acc": 0.9725925925925926,
        "val_f1": 0.9716650703704797,
        "lr": 0.0001
      },
      {
        "epoch": 14,
        "train_loss": 0.10041510914462716,
        "val_loss": 0.08965717491046449,
        "val_acc": 0.9688888888888889,
        "val_f1": 0.9673531228303321,
        "lr": 0.0001
      },
      {
        "epoch": 15,
        "train_loss": 0.09406366123141825,
        "val_loss": 0.07199553545447769,
        "val_acc": 0.9760493827160494,
        "val_f1": 0.9753535178277082,
        "lr": 0.0001
      },
      {
        "epoch": 16,
        "train_loss": 0.09761690388477168,
        "val_loss": 0.08212737926714192,
        "val_acc": 0.9745679012345679,
        "val_f1": 0.9731338362721866,
        "lr": 0.0001
      },
      {
        "epoch": 17,
        "train_loss": 0.08021088700663033,
        "val_loss": 0.08709308146668679,
        "val_acc": 0.9735802469135802,
        "val_f1": 0.9729368999852935,
        "lr": 0.0001
      },
      {
        "epoch": 18,
        "train_loss": 0.07702470674662983,
        "val_loss": 0.08518092836604274,
        "val_acc": 0.9745679012345679,
        "val_f1": 0.9733316965227345,
        "lr": 0.0001
      },
      {
        "epoch": 19,
        "train_loss": 0.07251022326551047,
        "val_loss": 0.06011755651291701,
        "val_acc": 0.9795061728395061,
        "val_f1": 0.9788754655532695,
        "lr": 0.0001
      },
      {
        "epoch": 20,
        "train_loss": 0.06822897567082672,
        "val_loss": 0.06180190128018902,
        "val_acc": 0.9780246913580247,
        "val_f1": 0.9773474751533427,
        "lr": 0.0001
      },
      {
        "epoch": 21,
        "train_loss": 0.07139082294137068,
        "val_loss": 0.07436759000244793,
        "val_acc": 0.980246913580247,
        "val_f1": 0.9795813453909019,
        "lr": 0.0001
      },
      {
        "epoch": 22,
        "train_loss": 0.0541616392895171,
        "val_loss": 0.08884776840125769,
        "val_acc": 0.9787654320987654,
        "val_f1": 0.9780129857469568,
        "lr": 0.0001
      },
      {
        "epoch": 23,
        "train_loss": 0.06002896305655695,
        "val_loss": 0.13197213207051506,
        "val_acc": 0.9698765432098766,
        "val_f1": 0.9694663588098793,
        "lr": 5e-05
      },
      {
        "epoch": 24,
        "train_loss": 0.037596972860013116,
        "val_loss": 0.08537580227866372,
        "val_acc": 0.9782716049382716,
        "val_f1": 0.9776703856721815,
        "lr": 5e-05
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/efficientnet_stage2_low_lr.json --checkpoints-output /kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_low_lr --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name efficientnet_b0 --experiment-name efficientnet_stage2_low_lr --seed 42 --epochs 30 --batch-size 16 --learning-rate 5e-05 --early-stopping-patience 5 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 3 --min-learning-rate 0.000000001 --augmentation-mode flips --resume-from /kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.971358024691358,
  "macro_f1_score": 0.9702862662389767,
  "precision": {
    "AnnualCrop": 0.9566160520607375,
    "Forest": 0.9911111111111112,
    "HerbaceousVegetation": 0.962882096069869,
    "Highway": 0.9832869080779945,
    "Industrial": 0.963254593175853,
    "Pasture": 0.9727891156462585,
    "PermanentCrop": 0.9536784741144414,
    "Residential": 0.9932279909706546,
    "River": 0.9413265306122449,
    "SeaLake": 0.9910112359550561
  },
  "recall": {
    "AnnualCrop": 0.98,
    "Forest": 0.9911111111111112,
    "HerbaceousVegetation": 0.98,
    "Highway": 0.9413333333333334,
    "Industrial": 0.9786666666666667,
    "Pasture": 0.9533333333333334,
    "PermanentCrop": 0.9333333333333333,
    "Residential": 0.9777777777777777,
    "River": 0.984,
    "SeaLake": 0.98
  },
  "confusion_matrix": [
    [
      441,
      0,
      0,
      0,
      0,
      1,
      4,
      0,
      3,
      1
    ],
    [
      0,
      446,
      2,
      0,
      0,
      2,
      0,
      0,
      0,
      0
    ],
    [
      0,
      1,
      441,
      0,
      0,
      1,
      6,
      0,
      0,
      1
    ],
    [
      1,
      0,
      1,
      353,
      5,
      0,
      1,
      0,
      13,
      1
    ],
    [
      0,
      0,
      0,
      0,
      367,
      0,
      4,
      3,
      1,
      0
    ],
    [
      7,
      2,
      4,
      0,
      0,
      286,
      0,
      0,
      0,
      1
    ],
    [
      9,
      1,
      9,
      2,
      1,
      3,
      350,
      0,
      0,
      0
    ],
    [
      0,
      0,
      1,
      2,
      5,
      0,
      2,
      440,
      0,
      0
    ],
    [
      1,
      0,
      0,
      2,
      3,
      0,
      0,
      0,
      369,
      0
    ],
    [
      2,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      6,
      441
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_low_lr/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/efficientnet_stage2_low_lr.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 24,
    "best_validation_loss": 0.0759248214855964,
    "best_validation_f1": 0.9754992414631765,
    "best_epoch": 19,
    "early_stopping_patience": 5,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 5e-05,
    "scheduler_factor": 0.5,
    "scheduler_patience": 3,
    "min_learning_rate": 1e-09,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 1.261912603769609,
        "val_loss": 0.8685379181996558,
        "val_acc": 0.837283950617284,
        "val_f1": 0.8320976339071846,
        "lr": 5e-05
      },
      {
        "epoch": 2,
        "train_loss": 0.726088727354789,
        "val_loss": 0.41968760034682434,
        "val_acc": 0.9012345679012346,
        "val_f1": 0.8991958661947003,
        "lr": 5e-05
      },
      {
        "epoch": 3,
        "train_loss": 0.5630239917661888,
        "val_loss": 0.33101987808037137,
        "val_acc": 0.9185185185185185,
        "val_f1": 0.9164907279436756,
        "lr": 5e-05
      },
      {
        "epoch": 4,
        "train_loss": 0.448132932801099,
        "val_loss": 0.24450516929358654,
        "val_acc": 0.9264197530864198,
        "val_f1": 0.9244332544821449,
        "lr": 5e-05
      },
      {
        "epoch": 5,
        "train_loss": 0.38581556968537495,
        "val_loss": 0.1883733704467084,
        "val_acc": 0.9439506172839506,
        "val_f1": 0.9419675465892376,
        "lr": 5e-05
      },
      {
        "epoch": 6,
        "train_loss": 0.32726132120703094,
        "val_loss": 0.2591582847143593,
        "val_acc": 0.9291358024691359,
        "val_f1": 0.9264688823913627,
        "lr": 5e-05
      },
      {
        "epoch": 7,
        "train_loss": 0.29416996833171805,
        "val_loss": 0.15586682304961783,
        "val_acc": 0.9496296296296296,
        "val_f1": 0.9477443174012837,
        "lr": 5e-05
      },
      {
        "epoch": 8,
        "train_loss": 0.2558028641814372,
        "val_loss": 0.18282408927939467,
        "val_acc": 0.9506172839506173,
        "val_f1": 0.9492368887774866,
        "lr": 5e-05
      },
      {
        "epoch": 9,
        "train_loss": 0.24178459334294367,
        "val_loss": 0.12448709738219897,
        "val_acc": 0.9595061728395061,
        "val_f1": 0.9579899505019769,
        "lr": 5e-05
      },
      {
        "epoch": 10,
        "train_loss": 0.20800694950888574,
        "val_loss": 0.21129777406786449,
        "val_acc": 0.9493827160493827,
        "val_f1": 0.9487090633736056,
        "lr": 5e-05
      },
      {
        "epoch": 11,
        "train_loss": 0.19462998640052218,
        "val_loss": 0.1038078289985126,
        "val_acc": 0.9666666666666667,
        "val_f1": 0.9652232028768275,
        "lr": 5e-05
      },
      {
        "epoch": 12,
        "train_loss": 0.174716870268364,
        "val_loss": 0.11041505966995184,
        "val_acc": 0.9634567901234568,
        "val_f1": 0.9622994421109101,
        "lr": 5e-05
      },
      {
        "epoch": 13,
        "train_loss": 0.17283836001809608,
        "val_loss": 0.11319526236252923,
        "val_acc": 0.9654320987654321,
        "val_f1": 0.9641634649547444,
        "lr": 5e-05
      },
      {
        "epoch": 14,
        "train_loss": 0.15377353809521,
        "val_loss": 0.10439101208151363,
        "val_acc": 0.9632098765432099,
        "val_f1": 0.9611846215555836,
        "lr": 5e-05
      },
      {
        "epoch": 15,
        "train_loss": 0.15146766675186268,
        "val_loss": 0.11282697349535137,
        "val_acc": 0.962716049382716,
        "val_f1": 0.9613904559897366,
        "lr": 2.5e-05
      },
      {
        "epoch": 16,
        "train_loss": 0.13455532379780324,
        "val_loss": 0.08057775080837963,
        "val_acc": 0.9708641975308642,
        "val_f1": 0.9698063322767163,
        "lr": 2.5e-05
      },
      {
        "epoch": 17,
        "train_loss": 0.12690534490741145,
        "val_loss": 0.10873773724697672,
        "val_acc": 0.9664197530864198,
        "val_f1": 0.9654678621007349,
        "lr": 2.5e-05
      },
      {
        "epoch": 18,
        "train_loss": 0.11141134194974384,
        "val_loss": 0.08576208429559036,
        "val_acc": 0.9708641975308642,
        "val_f1": 0.9691717621481333,
        "lr": 2.5e-05
      },
      {
        "epoch": 19,
        "train_loss": 0.1100016427834541,
        "val_loss": 0.0759248214855964,
        "val_acc": 0.9765432098765432,
        "val_f1": 0.9754992414631765,
        "lr": 2.5e-05
      },
      {
        "epoch": 20,
        "train_loss": 0.10327777162619926,
        "val_loss": 0.07651706538404965,
        "val_acc": 0.9755555555555555,
        "val_f1": 0.9746008583929594,
        "lr": 2.5e-05
      },
      {
        "epoch": 21,
        "train_loss": 0.10712717365138248,
        "val_loss": 0.08024617720039486,
        "val_acc": 0.9745679012345679,
        "val_f1": 0.9735631571644972,
        "lr": 2.5e-05
      },
      {
        "epoch": 22,
        "train_loss": 0.09411466523793971,
        "val_loss": 0.09143751495004795,
        "val_acc": 0.9723456790123457,
        "val_f1": 0.9715369314646749,
        "lr": 2.5e-05
      },
      {
        "epoch": 23,
        "train_loss": 0.08986494256655864,
        "val_loss": 0.1920196169439089,
        "val_acc": 0.9644444444444444,
        "val_f1": 0.9642555272815322,
        "lr": 1.25e-05
      },
      {
        "epoch": 24,
        "train_loss": 0.0819422604367724,
        "val_loss": 0.09654742515778607,
        "val_acc": 0.9720987654320987,
        "val_f1": 0.9711634330175183,
        "lr": 1.25e-05
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/efficientnet_stage2_no_aug.json --checkpoints-output /kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_no_aug --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name efficientnet_b0 --experiment-name efficientnet_stage2_no_aug --seed 42 --epochs 30 --batch-size 16 --learning-rate 0.0001 --early-stopping-patience 5 --early-stopping-min-delta 0.001 --scheduler-factor 0.5 --scheduler-patience 3 --min-learning-rate 0.000000001 --augmentation-mode none --resume-from /kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.pt --no-use-pretrained --no-freeze-backbone

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.9669135802469135,
  "macro_f1_score": 0.9659375027803587,
  "precision": {
    "AnnualCrop": 0.9818181818181818,
    "Forest": 0.9955257270693513,
    "HerbaceousVegetation": 0.9420600858369099,
    "Highway": 0.9746478873239437,
    "Industrial": 0.9836512261580381,
    "Pasture": 0.9764309764309764,
    "PermanentCrop": 0.9287598944591029,
    "Residential": 0.9823788546255506,
    "River": 0.9166666666666666,
    "SeaLake": 0.9844097995545658
  },
  "recall": {
    "AnnualCrop": 0.96,
    "Forest": 0.9888888888888889,
    "HerbaceousVegetation": 0.9755555555555555,
    "Highway": 0.9226666666666666,
    "Industrial": 0.9626666666666667,
    "Pasture": 0.9666666666666667,
    "PermanentCrop": 0.9386666666666666,
    "Residential": 0.9911111111111112,
    "River": 0.968,
    "SeaLake": 0.9822222222222222
  },
  "confusion_matrix": [
    [
      432,
      0,
      2,
      0,
      0,
      0,
      9,
      0,
      5,
      2
    ],
    [
      0,
      445,
      3,
      0,
      0,
      2,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      439,
      0,
      0,
      1,
      9,
      0,
      0,
      1
    ],
    [
      2,
      0,
      4,
      346,
      1,
      1,
      5,
      1,
      15,
      0
    ],
    [
      0,
      0,
      2,
      0,
      361,
      0,
      2,
      7,
      3,
      0
    ],
    [
      1,
      1,
      3,
      0,
      0,
      290,
      2,
      0,
      1,
      2
    ],
    [
      4,
      1,
      13,
      1,
      0,
      3,
      352,
      0,
      1,
      0
    ],
    [
      0,
      0,
      0,
      0,
      4,
      0,
      0,
      446,
      0,
      0
    ],
    [
      1,
      0,
      0,
      8,
      1,
      0,
      0,
      0,
      363,
      2
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      8,
      442
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_no_aug/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/efficientnet_stage2_no_aug.json",
  "training_state": {
    "epochs_requested": 30,
    "epochs_ran": 13,
    "best_validation_loss": 0.10531661067640145,
    "best_validation_f1": 0.9658553359375286,
    "best_epoch": 8,
    "early_stopping_patience": 5,
    "early_stopping_min_delta": 0.001,
    "learning_rate": 0.0001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 3,
    "min_learning_rate": 1e-09,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 0.9955685460757205,
        "val_loss": 1.2682095850748194,
        "val_acc": 0.8817283950617284,
        "val_f1": 0.8775265128533798,
        "lr": 0.0001
      },
      {
        "epoch": 2,
        "train_loss": 0.4900916497067071,
        "val_loss": 0.25321499475134845,
        "val_acc": 0.9256790123456791,
        "val_f1": 0.9233088742564339,
        "lr": 0.0001
      },
      {
        "epoch": 3,
        "train_loss": 0.3697544107648549,
        "val_loss": 0.19208429360351575,
        "val_acc": 0.942962962962963,
        "val_f1": 0.9408415234136646,
        "lr": 0.0001
      },
      {
        "epoch": 4,
        "train_loss": 0.2865059344106245,
        "val_loss": 0.159853755829389,
        "val_acc": 0.9444444444444444,
        "val_f1": 0.9424615162468466,
        "lr": 0.0001
      },
      {
        "epoch": 5,
        "train_loss": 0.2323897894040103,
        "val_loss": 0.12893465646475236,
        "val_acc": 0.9558024691358025,
        "val_f1": 0.9543359241907021,
        "lr": 0.0001
      },
      {
        "epoch": 6,
        "train_loss": 0.1982167504213525,
        "val_loss": 0.12915877198959314,
        "val_acc": 0.9609876543209876,
        "val_f1": 0.9593851553170802,
        "lr": 0.0001
      },
      {
        "epoch": 7,
        "train_loss": 0.1666043122065003,
        "val_loss": 0.13004262202714276,
        "val_acc": 0.96,
        "val_f1": 0.9589660806468082,
        "lr": 0.0001
      },
      {
        "epoch": 8,
        "train_loss": 0.1424813895787084,
        "val_loss": 0.10531661067640145,
        "val_acc": 0.9669135802469135,
        "val_f1": 0.9658553359375286,
        "lr": 0.0001
      },
      {
        "epoch": 9,
        "train_loss": 0.13149421075517065,
        "val_loss": 0.12205684873399551,
        "val_acc": 0.9619753086419753,
        "val_f1": 0.9607748640745412,
        "lr": 0.0001
      },
      {
        "epoch": 10,
        "train_loss": 0.10193557462075806,
        "val_loss": 0.11498955458201514,
        "val_acc": 0.965925925925926,
        "val_f1": 0.9648149719643543,
        "lr": 0.0001
      },
      {
        "epoch": 11,
        "train_loss": 0.09688963061338202,
        "val_loss": 0.668860267577148,
        "val_acc": 0.9414814814814815,
        "val_f1": 0.9422799012367544,
        "lr": 0.0001
      },
      {
        "epoch": 12,
        "train_loss": 0.08505130270398506,
        "val_loss": 0.2610824102481184,
        "val_acc": 0.9503703703703704,
        "val_f1": 0.9497589465731557,
        "lr": 5e-05
      },
      {
        "epoch": 13,
        "train_loss": 0.05805193751120358,
        "val_loss": 0.1479071577943084,
        "val_acc": 0.9619753086419753,
        "val_f1": 0.960905169749285,
        "lr": 5e-05
      }
    ]
  }
}
Saved summary CSV: /kaggle/working/artifacts/reports/efficientnet_experiment_summary.csv

,run_id,stage,augmentation_mode,learning_rate,freeze_backbone,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path
0,efficientnet_stage2_reference,stage2,flips,0.00010,False,30,24,0.978875,0.974321,0.973621,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
1,efficientnet_stage2_low_lr,stage2,flips,0.00005,False,30,24,0.975499,0.971358,0.970286,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
2,efficientnet_stage2_no_aug,stage2,none,0.00010,False,30,13,0.965855,0.966914,0.965938,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
3,efficientnet_stage1_reference,stage1,flips,0.00100,True,30,9,0.920765,0.926173,0.923145,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/st...

## Final Comparison Table and Export

In [7]:
best_row = efficientnet_summary.iloc[0]
print('Best EfficientNet configuration:')
print(best_row[['run_id', 'stage', 'augmentation_mode', 'learning_rate', 'test_accuracy', 'test_macro_f1']])

efficientnet_summary

Best EfficientNet configuration:
run_id               efficientnet_stage2_reference
stage                                       stage2
augmentation_mode                            flips
learning_rate                               0.0001
test_accuracy                             0.974321
test_macro_f1                             0.973621
Name: 0, dtype: object

,run_id,stage,augmentation_mode,learning_rate,freeze_backbone,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path
0,efficientnet_stage2_reference,stage2,flips,0.00010,False,30,24,0.978875,0.974321,0.973621,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
1,efficientnet_stage2_low_lr,stage2,flips,0.00005,False,30,24,0.975499,0.971358,0.970286,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
2,efficientnet_stage2_no_aug,stage2,none,0.00010,False,30,13,0.965855,0.966914,0.965938,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/ef...
3,efficientnet_stage1_reference,stage1,flips,0.00100,True,30,9,0.920765,0.926173,0.923145,/kaggle/working/artifacts/reports/efficientnet...,/kaggle/working/checkpoints/efficientnet_b0/st...

In [8]:
!zip -r /kaggle/working/efficientnet_results.zip /kaggle/working/artifacts /kaggle/working/checkpoints

  adding: kaggle/working/artifacts/ (stored 0%)
  adding: kaggle/working/artifacts/splits/ (stored 0%)
  adding: kaggle/working/artifacts/splits/train_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/split_manifest.json (deflated 33%)
  adding: kaggle/working/artifacts/splits/test_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/validation_split.json (deflated 98%)
  adding: kaggle/working/artifacts/reports/ (stored 0%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_no_aug.json (deflated 76%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage1_reference.json (deflated 75%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_reference.json (deflated 77%)
  adding: kaggle/working/artifacts/reports/efficientnet_experiment_summary.csv (deflated 67%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_low_lr.json (deflated 77%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_no_aug.training_log.tmp.json (deflated 73%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_low_lr.training_log.tmp.json (deflated 76%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage2_reference.training_log.tmp.json (deflated 76%)
  adding: kaggle/working/artifacts/reports/efficientnet_stage1_reference.training_log.tmp.json (deflated 71%)
  adding: kaggle/working/checkpoints/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/stage1/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.pt (deflated 8%)
  adding: kaggle/working/checkpoints/efficientnet_b0/stage1/best_checkpoint.metadata.json (deflated 73%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_reference/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_reference/best_checkpoint.pt (deflated 8%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_reference/best_checkpoint.metadata.json (deflated 76%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_no_aug/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_no_aug/best_checkpoint.pt (deflated 8%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_no_aug/best_checkpoint.metadata.json (deflated 74%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_low_lr/ (stored 0%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_low_lr/best_checkpoint.pt (deflated 8%)
  adding: kaggle/working/checkpoints/efficientnet_b0/efficientnet_stage2_low_lr/best_checkpoint.metadata.json (deflated 76%)