# EuroSAT Baseline CNN Kaggle Runner

This notebook runs multiple Baseline CNN configurations through CLI overrides.
It uses one canonical defaults file and does not rely on separate per-experiment config files.

In [1]:
import os
import shutil
import subprocess
from pathlib import Path
from kaggle_secrets import UserSecretsClient

WORKING = Path('/kaggle/working')
REPO = WORKING / 'satellite-land-classification-dl'
REPOSITORY_URL = 'https://github.com/milanovicmilos/satellite-land-classification-dl.git'

if REPO.exists():
    shutil.rmtree(REPO)

user_secrets = UserSecretsClient()
token = user_secrets.get_secret("GH_TOKEN")

if not token:
    raise RuntimeError('Missing GH_TOKEN in Kaggle Secrets.')

auth_url = f'https://x-access-token:{token}@github.com/milanovicmilos/satellite-land-classification-dl.git'
subprocess.run(['git', 'clone', auth_url, REPO.as_posix()], check=True)
subprocess.run(
    ['git', '-C', REPO.as_posix(), 'remote', 'set-url', 'origin', REPOSITORY_URL],
    check=True,
)

target_branches = ['refactor/infrastructure-and-configs', 'dev', 'feature/efficientnet-optimization', 'main']
success = False

for branch in target_branches:
    checkout = subprocess.run(
        ['git', '-C', REPO.as_posix(), 'checkout', branch],
        capture_output=True,
        text=True,
    )
    if checkout.returncode == 0:
        print(f"Checked out: {branch}")
        success = True
        break

if not success:
    raise RuntimeError("Could not checkout to any target branch.")

%cd {REPO.as_posix()}

Cloning into '/kaggle/working/satellite-land-classification-dl'...

Checked out: refactor/infrastructure-and-configs
/kaggle/working/satellite-land-classification-dl

In [2]:
!python -m pip install --upgrade pip
!python -m pip install -e .

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.0.1
Obtaining file:///kaggle/working/satellite-land-classification-dl
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: torch>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (0.24.0+cu126)
Requirement already satisfied: Pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from eurosat-land-classification==0.1.0) (11.3.0)
Collecting numpy>=2.2.0 (from eurosat-land-classification==0.1.0)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5.0->eurosat-land-classification==0.1.0) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.5.0->eurosat-land-classification==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.5.0->eurosat-land-classification==0.1.0) (3.0.3)
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 32.6 MB/s  0:00:00
Building wheels for collected packages: eurosat-land-classification
  Building editable for eurosat-land-classification (pyproject.toml) ... done
  Created wheel for eurosat-land-classification: filename=eurosat_land_classification-0.1.0-0.editable-py3-none-any.whl size=3401 sha256=c3a9ccadf734b374347c9d66370fa228ba984de2a7f0cbaf2b6362c21e8088c3
  Stored in directory: /tmp/pip-ephem-wheel-cache-5grnro7i/wheels/3a/51/ed/94edbae1ff9e3c632e6ce74bfe624ca59243f59877810503f8
Successfully built eurosat-land-classification
Installing collected packages: numpy, eurosat-land-classification
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [eurosat-land-classification]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.31.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.1 requires numpy<2.4,>=1.22, but you have numpy 2.4.4 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
Successfully installed eurosat-land-classification-0.1.0 numpy-2.4.4

In [3]:
import json
import pandas as pd

DATASET_INPUT_ROOT = Path('/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT')
assert DATASET_INPUT_ROOT.exists(), f'Missing dataset path: {DATASET_INPUT_ROOT}'

BASE_CONFIG = 'configs/experiment.defaults.json'
SPLITS_OUTPUT = '/kaggle/working/artifacts/splits'
REPORTS_ROOT = Path('/kaggle/working/artifacts/reports')
CHECKPOINTS_ROOT = Path('/kaggle/working/checkpoints/baseline_cnn')
SUMMARY_CSV = REPORTS_ROOT / 'baseline_experiment_summary.csv'

REPORTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINTS_ROOT.mkdir(parents=True, exist_ok=True)

SEED = 42

BASELINE_EXPERIMENTS = [
    {
        'run_id': 'baseline_reference_none',
        'epochs': 50,
        'batch_size': 16,
        'learning_rate': 0.001,
        'early_stopping_patience': 10,
        'scheduler_patience': 5,
        'augmentation_mode': 'none',
    },
    {
        'run_id': 'baseline_flips',
        'epochs': 50,
        'batch_size': 16,
        'learning_rate': 0.001,
        'early_stopping_patience': 10,
        'scheduler_patience': 5,
        'augmentation_mode': 'flips',
    },
    {
        'run_id': 'baseline_flips_low_lr',
        'epochs': 50,
        'batch_size': 16,
        'learning_rate': 0.0005,
        'early_stopping_patience': 10,
        'scheduler_patience': 5,
        'augmentation_mode': 'flips',
    },
]


def run_cmd(cmd: list[str]) -> None:
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)


print('Prepared baseline experiment grid:')
for experiment in BASELINE_EXPERIMENTS:
    print(experiment)

Prepared baseline experiment grid:
{'run_id': 'baseline_reference_none', 'epochs': 50, 'batch_size': 16, 'learning_rate': 0.001, 'early_stopping_patience': 10, 'scheduler_patience': 5, 'augmentation_mode': 'none'}
{'run_id': 'baseline_flips', 'epochs': 50, 'batch_size': 16, 'learning_rate': 0.001, 'early_stopping_patience': 10, 'scheduler_patience': 5, 'augmentation_mode': 'flips'}
{'run_id': 'baseline_flips_low_lr', 'epochs': 50, 'batch_size': 16, 'learning_rate': 0.0005, 'early_stopping_patience': 10, 'scheduler_patience': 5, 'augmentation_mode': 'flips'}

In [4]:
prepare_cmd = [
    'python',
    'run.py',
    '--prepare-dataset',
    '--config',
    BASE_CONFIG,
    '--defaults',
    'configs/experiment.defaults.json',
    '--splits-output',
    SPLITS_OUTPUT,
    '--dataset-root',
    DATASET_INPUT_ROOT.as_posix(),
    '--model-name',
    'baseline_cnn',
    '--seed',
    str(SEED),
    '--train-ratio',
    '0.7',
    '--validation-ratio',
    '0.15',
    '--test-ratio',
    '0.15',
    '--stratified',
]

run_cmd(prepare_cmd)

python run.py --prepare-dataset --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name baseline_cnn --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified
{
  "dataset_root": "/kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT",
  "seed": 42,
  "class_count": 10,
  "total_samples": 27000,
  "train_samples": 18900,
  "validation_samples": 4050,
  "test_samples": 4050,
  "artifacts": {
    "train": "/kaggle/working/artifacts/splits/train_split.json",
    "validation": "/kaggle/working/artifacts/splits/validation_split.json",
    "test": "/kaggle/working/artifacts/splits/test_split.json",
    "manifest": "/kaggle/working/artifacts/splits/split_manifest.json"
  }
}

In [5]:
baseline_rows = []

for experiment in BASELINE_EXPERIMENTS:
    run_id = experiment['run_id']
    report_path = REPORTS_ROOT / f"{run_id}.json"
    checkpoints_output = CHECKPOINTS_ROOT / run_id

    run_cmd(
        [
            'python',
            'run.py',
            '--run-baseline',
            '--config',
            BASE_CONFIG,
            '--defaults',
            'configs/experiment.defaults.json',
            '--splits-output',
            SPLITS_OUTPUT,
            '--reports-output',
            report_path.as_posix(),
            '--checkpoints-output',
            checkpoints_output.as_posix(),
            '--dataset-root',
            DATASET_INPUT_ROOT.as_posix(),
            '--model-name',
            'baseline_cnn',
            '--experiment-name',
            run_id,
            '--seed',
            str(SEED),
            '--train-ratio',
            '0.7',
            '--validation-ratio',
            '0.15',
            '--test-ratio',
            '0.15',
            '--stratified',
            '--epochs',
            str(experiment['epochs']),
            '--batch-size',
            str(experiment['batch_size']),
            '--learning-rate',
            str(experiment['learning_rate']),
            '--early-stopping-patience',
            str(experiment['early_stopping_patience']),
            '--early-stopping-min-delta',
            '0.0',
            '--scheduler-factor',
            '0.5',
            '--scheduler-patience',
            str(experiment['scheduler_patience']),
            '--min-learning-rate',
            '0.000001',
            '--augmentation-mode',
            experiment['augmentation_mode'],
        ]
    )

    payload = json.loads(report_path.read_text(encoding='utf-8'))
    metrics = payload['metrics']
    training_state = payload['metadata']['training_state']

    baseline_rows.append(
        {
            'run_id': run_id,
            'augmentation_mode': experiment['augmentation_mode'],
            'learning_rate': experiment['learning_rate'],
            'epochs_requested': experiment['epochs'],
            'epochs_ran': training_state.get('epochs_ran'),
            'val_f1_best': training_state.get('best_validation_f1'),
            'test_accuracy': metrics['accuracy'],
            'test_macro_f1': metrics['macro_f1_score'],
            'report_path': report_path.as_posix(),
            'checkpoint_path': payload['metadata'].get('checkpoint_path'),
        }
    )

baseline_summary = pd.DataFrame(baseline_rows).sort_values(
    by=['test_macro_f1', 'test_accuracy'],
    ascending=False,
).reset_index(drop=True)

baseline_summary.to_csv(SUMMARY_CSV, index=False)
print('Saved summary CSV:', SUMMARY_CSV)
baseline_summary

python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/baseline_reference_none.json --checkpoints-output /kaggle/working/checkpoints/baseline_cnn/baseline_reference_none --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name baseline_cnn --experiment-name baseline_reference_none --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified --epochs 50 --batch-size 16 --learning-rate 0.001 --early-stopping-patience 10 --early-stopping-min-delta 0.0 --scheduler-factor 0.5 --scheduler-patience 5 --min-learning-rate 0.000001 --augmentation-mode none

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.9123456790123456,
  "macro_f1_score": 0.9089490183702811,
  "precision": {
    "AnnualCrop": 0.92,
    "Forest": 0.9671772428884027,
    "HerbaceousVegetation": 0.8931818181818182,
    "Highway": 0.8684931506849315,
    "Industrial": 0.9536784741144414,
    "Pasture": 0.8976897689768977,
    "PermanentCrop": 0.808,
    "Residential": 0.9322033898305084,
    "River": 0.8670212765957447,
    "SeaLake": 0.9842696629213483
  },
  "recall": {
    "AnnualCrop": 0.92,
    "Forest": 0.9822222222222222,
    "HerbaceousVegetation": 0.8733333333333333,
    "Highway": 0.8453333333333334,
    "Industrial": 0.9333333333333333,
    "Pasture": 0.9066666666666666,
    "PermanentCrop": 0.808,
    "Residential": 0.9777777777777777,
    "River": 0.8693333333333333,
    "SeaLake": 0.9733333333333334
  },
  "confusion_matrix": [
    [
      414,
      0,
      1,
      1,
      0,
      6,
      12,
      0,
      12,
      4
    ],
    [
      0,
      442,
      2,
      0,
      0,
      5,
      0,
      0,
      1,
      0
    ],
    [
      2,
      1,
      393,
      7,
      3,
      1,
      31,
      7,
      5,
      0
    ],
    [
      6,
      0,
      2,
      317,
      5,
      2,
      18,
      7,
      18,
      0
    ],
    [
      0,
      0,
      3,
      7,
      350,
      0,
      1,
      13,
      1,
      0
    ],
    [
      5,
      8,
      6,
      2,
      0,
      272,
      2,
      0,
      4,
      1
    ],
    [
      14,
      0,
      25,
      13,
      2,
      9,
      303,
      5,
      4,
      0
    ],
    [
      0,
      0,
      2,
      1,
      6,
      0,
      1,
      440,
      0,
      0
    ],
    [
      6,
      5,
      5,
      16,
      1,
      7,
      7,
      0,
      326,
      2
    ],
    [
      3,
      1,
      1,
      1,
      0,
      1,
      0,
      0,
      5,
      438
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/baseline_cnn/baseline_reference_none/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/baseline_reference_none.json",
  "training_state": {
    "epochs_requested": 50,
    "epochs_ran": 50,
    "best_validation_loss": 0.6165213557906524,
    "best_validation_f1": 0.9153625672952819,
    "best_epoch": 46,
    "early_stopping_patience": 10,
    "early_stopping_min_delta": 0.0,
    "learning_rate": 0.001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "min_learning_rate": 1e-06,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 1.2602494820422934,
        "val_loss": 0.8203962167915632,
        "val_acc": 0.685679012345679,
        "val_f1": 0.6657178345071146,
        "lr": 0.001
      },
      {
        "epoch": 2,
        "train_loss": 0.8177318729447632,
        "val_loss": 0.6545168904910289,
        "val_acc": 0.7804938271604939,
        "val_f1": 0.7713842277289491,
        "lr": 0.001
      },
      {
        "epoch": 3,
        "train_loss": 0.697316739739702,
        "val_loss": 0.5328502309889951,
        "val_acc": 0.8101234567901234,
        "val_f1": 0.8018723015204168,
        "lr": 0.001
      },
      {
        "epoch": 4,
        "train_loss": 0.5954635950394743,
        "val_loss": 0.5040982096972986,
        "val_acc": 0.814320987654321,
        "val_f1": 0.8086343257403057,
        "lr": 0.001
      },
      {
        "epoch": 5,
        "train_loss": 0.5161453277982028,
        "val_loss": 0.44995143072952404,
        "val_acc": 0.84,
        "val_f1": 0.8319929656805469,
        "lr": 0.001
      },
      {
        "epoch": 6,
        "train_loss": 0.46172616411908174,
        "val_loss": 0.41724900208119353,
        "val_acc": 0.86,
        "val_f1": 0.855356387169649,
        "lr": 0.001
      },
      {
        "epoch": 7,
        "train_loss": 0.39876623080756557,
        "val_loss": 0.4063213528426113,
        "val_acc": 0.860246913580247,
        "val_f1": 0.8547748922072038,
        "lr": 0.001
      },
      {
        "epoch": 8,
        "train_loss": 0.3462250592185471,
        "val_loss": 0.38843790411536205,
        "val_acc": 0.8659259259259259,
        "val_f1": 0.860397069957864,
        "lr": 0.001
      },
      {
        "epoch": 9,
        "train_loss": 0.2925938335357647,
        "val_loss": 0.4626881919430448,
        "val_acc": 0.8464197530864197,
        "val_f1": 0.8398569385959979,
        "lr": 0.001
      },
      {
        "epoch": 10,
        "train_loss": 0.2608563598141377,
        "val_loss": 0.400654422347765,
        "val_acc": 0.8738271604938271,
        "val_f1": 0.8719504299864409,
        "lr": 0.001
      },
      {
        "epoch": 11,
        "train_loss": 0.24320481655537743,
        "val_loss": 0.4571482556245077,
        "val_acc": 0.8395061728395061,
        "val_f1": 0.8346306220690807,
        "lr": 0.001
      },
      {
        "epoch": 12,
        "train_loss": 0.2031840786791695,
        "val_loss": 0.37194534708052784,
        "val_acc": 0.8819753086419753,
        "val_f1": 0.8788633952277317,
        "lr": 0.001
      },
      {
        "epoch": 13,
        "train_loss": 0.18124075489222702,
        "val_loss": 0.39872465750310704,
        "val_acc": 0.8775308641975309,
        "val_f1": 0.8742188686988989,
        "lr": 0.001
      },
      {
        "epoch": 14,
        "train_loss": 0.16753207731995157,
        "val_loss": 0.4387273576759128,
        "val_acc": 0.8861728395061729,
        "val_f1": 0.8830329376486065,
        "lr": 0.001
      },
      {
        "epoch": 15,
        "train_loss": 0.1488272924680978,
        "val_loss": 0.4260696649262799,
        "val_acc": 0.8802469135802469,
        "val_f1": 0.8774696253714982,
        "lr": 0.001
      },
      {
        "epoch": 16,
        "train_loss": 0.1413381513061499,
        "val_loss": 0.5774560683714771,
        "val_acc": 0.8498765432098765,
        "val_f1": 0.8453409521435595,
        "lr": 0.001
      },
      {
        "epoch": 17,
        "train_loss": 0.13617869128549728,
        "val_loss": 0.6474380719067078,
        "val_acc": 0.837037037037037,
        "val_f1": 0.8324792834031325,
        "lr": 0.001
      },
      {
        "epoch": 18,
        "train_loss": 0.12065170901267007,
        "val_loss": 0.5605784512303016,
        "val_acc": 0.8649382716049383,
        "val_f1": 0.8599620167330979,
        "lr": 0.0005
      },
      {
        "epoch": 19,
        "train_loss": 0.051868543080499555,
        "val_loss": 0.47750404764277693,
        "val_acc": 0.9039506172839507,
        "val_f1": 0.9013764874182165,
        "lr": 0.0005
      },
      {
        "epoch": 20,
        "train_loss": 0.04622498331497675,
        "val_loss": 0.4845849847483371,
        "val_acc": 0.8953086419753087,
        "val_f1": 0.8916840055273314,
        "lr": 0.0005
      },
      {
        "epoch": 21,
        "train_loss": 0.0544443020660491,
        "val_loss": 0.481471775710006,
        "val_acc": 0.9041975308641975,
        "val_f1": 0.9008165130230609,
        "lr": 0.0005
      },
      {
        "epoch": 22,
        "train_loss": 0.04553387564253791,
        "val_loss": 0.48862304043183663,
        "val_acc": 0.9007407407407407,
        "val_f1": 0.8975532700341218,
        "lr": 0.0005
      },
      {
        "epoch": 23,
        "train_loss": 0.03704635586506092,
        "val_loss": 0.5159116816107852,
        "val_acc": 0.9032098765432098,
        "val_f1": 0.899500390869863,
        "lr": 0.0005
      },
      {
        "epoch": 24,
        "train_loss": 0.04297871771339875,
        "val_loss": 0.49618569545420155,
        "val_acc": 0.9037037037037037,
        "val_f1": 0.9004878434690141,
        "lr": 0.00025
      },
      {
        "epoch": 25,
        "train_loss": 0.018033467814094,
        "val_loss": 0.49467117351454754,
        "val_acc": 0.9128395061728395,
        "val_f1": 0.9097277084170317,
        "lr": 0.00025
      },
      {
        "epoch": 26,
        "train_loss": 0.015849087600792733,
        "val_loss": 0.5266348311647722,
        "val_acc": 0.9088888888888889,
        "val_f1": 0.9056700623213322,
        "lr": 0.00025
      },
      {
        "epoch": 27,
        "train_loss": 0.016369747933528578,
        "val_loss": 0.5370998656969783,
        "val_acc": 0.9019753086419753,
        "val_f1": 0.8987984526068175,
        "lr": 0.00025
      },
      {
        "epoch": 28,
        "train_loss": 0.01589765333799926,
        "val_loss": 0.5530449307064698,
        "val_acc": 0.9076543209876543,
        "val_f1": 0.904049914136768,
        "lr": 0.00025
      },
      {
        "epoch": 29,
        "train_loss": 0.015142630296093283,
        "val_loss": 0.539275831577659,
        "val_acc": 0.9106172839506173,
        "val_f1": 0.9075180829293268,
        "lr": 0.00025
      },
      {
        "epoch": 30,
        "train_loss": 0.014148516139616062,
        "val_loss": 0.5378157497385373,
        "val_acc": 0.9108641975308642,
        "val_f1": 0.9075505046792159,
        "lr": 0.000125
      },
      {
        "epoch": 31,
        "train_loss": 0.008159627970852783,
        "val_loss": 0.5677576779367126,
        "val_acc": 0.9103703703703704,
        "val_f1": 0.9065148462006098,
        "lr": 0.000125
      },
      {
        "epoch": 32,
        "train_loss": 0.0072129946221763715,
        "val_loss": 0.5649987454452932,
        "val_acc": 0.9079012345679013,
        "val_f1": 0.9044660059422569,
        "lr": 0.000125
      },
      {
        "epoch": 33,
        "train_loss": 0.00746998685616733,
        "val_loss": 0.6255769866778769,
        "val_acc": 0.9074074074074074,
        "val_f1": 0.9041421853057298,
        "lr": 0.000125
      },
      {
        "epoch": 34,
        "train_loss": 0.007877473678776706,
        "val_loss": 0.5734372253704142,
        "val_acc": 0.9160493827160494,
        "val_f1": 0.9132309923842177,
        "lr": 0.000125
      },
      {
        "epoch": 35,
        "train_loss": 0.007073014072083773,
        "val_loss": 0.6114805922024329,
        "val_acc": 0.9106172839506173,
        "val_f1": 0.9078928486150835,
        "lr": 0.000125
      },
      {
        "epoch": 36,
        "train_loss": 0.0066461999948734165,
        "val_loss": 0.6147651792091412,
        "val_acc": 0.9133333333333333,
        "val_f1": 0.9107800895238813,
        "lr": 6.25e-05
      },
      {
        "epoch": 37,
        "train_loss": 0.005759098963474035,
        "val_loss": 0.5898709635538973,
        "val_acc": 0.9133333333333333,
        "val_f1": 0.9105537938495043,
        "lr": 6.25e-05
      },
      {
        "epoch": 38,
        "train_loss": 0.004117816929338612,
        "val_loss": 0.6318436533840779,
        "val_acc": 0.9130864197530865,
        "val_f1": 0.910418387550292,
        "lr": 6.25e-05
      },
      {
        "epoch": 39,
        "train_loss": 0.004067890604024128,
        "val_loss": 0.6284027146399587,
        "val_acc": 0.9150617283950617,
        "val_f1": 0.9120802394361915,
        "lr": 6.25e-05
      },
      {
        "epoch": 40,
        "train_loss": 0.003472054090664419,
        "val_loss": 0.6000318957198076,
        "val_acc": 0.9153086419753086,
        "val_f1": 0.9125984435205098,
        "lr": 6.25e-05
      },
      {
        "epoch": 41,
        "train_loss": 0.003540757177477883,
        "val_loss": 0.6190711774317517,
        "val_acc": 0.9177777777777778,
        "val_f1": 0.9148743191408275,
        "lr": 6.25e-05
      },
      {
        "epoch": 42,
        "train_loss": 0.002878512738899445,
        "val_loss": 0.6362824675770611,
        "val_acc": 0.9153086419753086,
        "val_f1": 0.9125082453630075,
        "lr": 3.125e-05
      },
      {
        "epoch": 43,
        "train_loss": 0.004262351652276488,
        "val_loss": 0.6387170053668967,
        "val_acc": 0.9150617283950617,
        "val_f1": 0.9122858992444268,
        "lr": 3.125e-05
      },
      {
        "epoch": 44,
        "train_loss": 0.00242536168670463,
        "val_loss": 0.6668548278793324,
        "val_acc": 0.9138271604938272,
        "val_f1": 0.9108999658543262,
        "lr": 3.125e-05
      },
      {
        "epoch": 45,
        "train_loss": 0.0028538100424196932,
        "val_loss": 0.6400792133217149,
        "val_acc": 0.9153086419753086,
        "val_f1": 0.9126774443838052,
        "lr": 3.125e-05
      },
      {
        "epoch": 46,
        "train_loss": 0.002743101764445277,
        "val_loss": 0.6165213557906524,
        "val_acc": 0.9180246913580247,
        "val_f1": 0.9153625672952819,
        "lr": 3.125e-05
      },
      {
        "epoch": 47,
        "train_loss": 0.002574638608117008,
        "val_loss": 0.6209284135563821,
        "val_acc": 0.9158024691358024,
        "val_f1": 0.913237907395627,
        "lr": 3.125e-05
      },
      {
        "epoch": 48,
        "train_loss": 0.001959605630833609,
        "val_loss": 0.6610417784801549,
        "val_acc": 0.9133333333333333,
        "val_f1": 0.9104400955814572,
        "lr": 1.5625e-05
      },
      {
        "epoch": 49,
        "train_loss": 0.002437081597198398,
        "val_loss": 0.6250877867177338,
        "val_acc": 0.9155555555555556,
        "val_f1": 0.9127548937151596,
        "lr": 1.5625e-05
      },
      {
        "epoch": 50,
        "train_loss": 0.002678149437476427,
        "val_loss": 0.6452783383982069,
        "val_acc": 0.9165432098765433,
        "val_f1": 0.9137650987041814,
        "lr": 1.5625e-05
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/baseline_flips.json --checkpoints-output /kaggle/working/checkpoints/baseline_cnn/baseline_flips --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name baseline_cnn --experiment-name baseline_flips --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified --epochs 50 --batch-size 16 --learning-rate 0.001 --early-stopping-patience 10 --early-stopping-min-delta 0.0 --scheduler-factor 0.5 --scheduler-patience 5 --min-learning-rate 0.000001 --augmentation-mode flips

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.9479012345679012,
  "macro_f1_score": 0.9462378044166989,
  "precision": {
    "AnnualCrop": 0.9502262443438914,
    "Forest": 0.9910313901345291,
    "HerbaceousVegetation": 0.9461358313817331,
    "Highway": 0.9197860962566845,
    "Industrial": 0.9730458221024259,
    "Pasture": 0.935064935064935,
    "PermanentCrop": 0.8798955613577023,
    "Residential": 0.9889135254988913,
    "River": 0.8888888888888888,
    "SeaLake": 0.9845132743362832
  },
  "recall": {
    "AnnualCrop": 0.9333333333333333,
    "Forest": 0.9822222222222222,
    "HerbaceousVegetation": 0.8977777777777778,
    "Highway": 0.9173333333333333,
    "Industrial": 0.9626666666666667,
    "Pasture": 0.96,
    "PermanentCrop": 0.8986666666666666,
    "Residential": 0.9911111111111112,
    "River": 0.9386666666666666,
    "SeaLake": 0.9888888888888889
  },
  "confusion_matrix": [
    [
      420,
      0,
      1,
      0,
      0,
      5,
      10,
      0,
      9,
      5
    ],
    [
      1,
      442,
      2,
      0,
      0,
      5,
      0,
      0,
      0,
      0
    ],
    [
      2,
      1,
      404,
      2,
      3,
      3,
      30,
      1,
      4,
      0
    ],
    [
      3,
      0,
      2,
      344,
      3,
      1,
      3,
      1,
      17,
      1
    ],
    [
      0,
      0,
      0,
      9,
      361,
      0,
      0,
      3,
      2,
      0
    ],
    [
      1,
      1,
      3,
      1,
      0,
      288,
      2,
      0,
      4,
      0
    ],
    [
      8,
      0,
      12,
      9,
      1,
      4,
      337,
      0,
      4,
      0
    ],
    [
      0,
      0,
      0,
      1,
      2,
      0,
      1,
      446,
      0,
      0
    ],
    [
      6,
      2,
      3,
      8,
      1,
      2,
      0,
      0,
      352,
      1
    ],
    [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      4,
      445
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/baseline_cnn/baseline_flips/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/baseline_flips.json",
  "training_state": {
    "epochs_requested": 50,
    "epochs_ran": 50,
    "best_validation_loss": 0.17263172961874151,
    "best_validation_f1": 0.9518129996269049,
    "best_epoch": 50,
    "early_stopping_patience": 10,
    "early_stopping_min_delta": 0.0,
    "learning_rate": 0.001,
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "min_learning_rate": 1e-06,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 1.2590114237794214,
        "val_loss": 0.8714688365516348,
        "val_acc": 0.6795061728395062,
        "val_f1": 0.6647597717146869,
        "lr": 0.001
      },
      {
        "epoch": 2,
        "train_loss": 0.8072974594237438,
        "val_loss": 0.7019185895745562,
        "val_acc": 0.7395061728395061,
        "val_f1": 0.7358558580517354,
        "lr": 0.001
      },
      {
        "epoch": 3,
        "train_loss": 0.7372623951238928,
        "val_loss": 0.7936361191984941,
        "val_acc": 0.7138271604938271,
        "val_f1": 0.7067386265695041,
        "lr": 0.001
      },
      {
        "epoch": 4,
        "train_loss": 0.6498030952025086,
        "val_loss": 0.5578621123109827,
        "val_acc": 0.7985185185185185,
        "val_f1": 0.793878621400618,
        "lr": 0.001
      },
      {
        "epoch": 5,
        "train_loss": 0.598580610561744,
        "val_loss": 0.47958861157943417,
        "val_acc": 0.822716049382716,
        "val_f1": 0.8182570686411699,
        "lr": 0.001
      },
      {
        "epoch": 6,
        "train_loss": 0.5381768729329715,
        "val_loss": 0.4332287443826281,
        "val_acc": 0.8464197530864197,
        "val_f1": 0.8412638885622916,
        "lr": 0.001
      },
      {
        "epoch": 7,
        "train_loss": 0.5092236564798807,
        "val_loss": 0.42783643998660326,
        "val_acc": 0.8414814814814815,
        "val_f1": 0.8385032285664114,
        "lr": 0.001
      },
      {
        "epoch": 8,
        "train_loss": 0.45950663771146244,
        "val_loss": 0.5332627618216953,
        "val_acc": 0.8088888888888889,
        "val_f1": 0.8019309332260585,
        "lr": 0.001
      },
      {
        "epoch": 9,
        "train_loss": 0.44130347878869164,
        "val_loss": 0.4550927451222321,
        "val_acc": 0.8291358024691358,
        "val_f1": 0.8213205197483904,
        "lr": 0.001
      },
      {
        "epoch": 10,
        "train_loss": 0.41145521875111585,
        "val_loss": 0.3323507289487894,
        "val_acc": 0.8787654320987655,
        "val_f1": 0.8738206571483296,
        "lr": 0.001
      },
      {
        "epoch": 11,
        "train_loss": 0.3901495876739372,
        "val_loss": 0.33920401283237905,
        "val_acc": 0.8837037037037037,
        "val_f1": 0.8810888580890432,
        "lr": 0.001
      },
      {
        "epoch": 12,
        "train_loss": 0.3653093802296697,
        "val_loss": 0.35314137785065924,
        "val_acc": 0.8701234567901235,
        "val_f1": 0.8680087857399792,
        "lr": 0.001
      },
      {
        "epoch": 13,
        "train_loss": 0.3395417004023157,
        "val_loss": 0.37674273603627045,
        "val_acc": 0.8674074074074074,
        "val_f1": 0.863380673949832,
        "lr": 0.001
      },
      {
        "epoch": 14,
        "train_loss": 0.31436657560941983,
        "val_loss": 0.32462802594417606,
        "val_acc": 0.8827160493827161,
        "val_f1": 0.8802656549762766,
        "lr": 0.001
      },
      {
        "epoch": 15,
        "train_loss": 0.31685539898533505,
        "val_loss": 0.4129532081381576,
        "val_acc": 0.8629629629629629,
        "val_f1": 0.8600258606653222,
        "lr": 0.001
      },
      {
        "epoch": 16,
        "train_loss": 0.3062984647553149,
        "val_loss": 0.3217660775728978,
        "val_acc": 0.8849382716049383,
        "val_f1": 0.881750772073325,
        "lr": 0.001
      },
      {
        "epoch": 17,
        "train_loss": 0.29927808731753386,
        "val_loss": 0.2472148538256833,
        "val_acc": 0.914320987654321,
        "val_f1": 0.912470879221744,
        "lr": 0.001
      },
      {
        "epoch": 18,
        "train_loss": 0.28098790003648644,
        "val_loss": 0.30383490796433704,
        "val_acc": 0.8985185185185185,
        "val_f1": 0.8961177239252567,
        "lr": 0.001
      },
      {
        "epoch": 19,
        "train_loss": 0.2752463749756441,
        "val_loss": 0.3159895122965202,
        "val_acc": 0.8930864197530864,
        "val_f1": 0.8904543623495357,
        "lr": 0.001
      },
      {
        "epoch": 20,
        "train_loss": 0.2616265892467183,
        "val_loss": 0.2635397218644672,
        "val_acc": 0.9106172839506173,
        "val_f1": 0.9088877126285576,
        "lr": 0.001
      },
      {
        "epoch": 21,
        "train_loss": 0.2530524279772936,
        "val_loss": 0.24252727467767918,
        "val_acc": 0.914074074074074,
        "val_f1": 0.912207035207642,
        "lr": 0.001
      },
      {
        "epoch": 22,
        "train_loss": 0.2576490833661196,
        "val_loss": 0.23121409990409567,
        "val_acc": 0.9241975308641975,
        "val_f1": 0.9225782447561869,
        "lr": 0.001
      },
      {
        "epoch": 23,
        "train_loss": 0.24846901914992017,
        "val_loss": 0.22114890797366377,
        "val_acc": 0.9246913580246914,
        "val_f1": 0.923297060798661,
        "lr": 0.001
      },
      {
        "epoch": 24,
        "train_loss": 0.2416066843890246,
        "val_loss": 0.1988063406753765,
        "val_acc": 0.9333333333333333,
        "val_f1": 0.9318763534959448,
        "lr": 0.001
      },
      {
        "epoch": 25,
        "train_loss": 0.23617169919168474,
        "val_loss": 0.2648423274145311,
        "val_acc": 0.9128395061728395,
        "val_f1": 0.9105740399569868,
        "lr": 0.001
      },
      {
        "epoch": 26,
        "train_loss": 0.22590427079497816,
        "val_loss": 0.2775719849323507,
        "val_acc": 0.9108641975308642,
        "val_f1": 0.9088431456131522,
        "lr": 0.001
      },
      {
        "epoch": 27,
        "train_loss": 0.22222258937011305,
        "val_loss": 0.20469468330055118,
        "val_acc": 0.9330864197530864,
        "val_f1": 0.9313024987455695,
        "lr": 0.001
      },
      {
        "epoch": 28,
        "train_loss": 0.2180345930226459,
        "val_loss": 0.2256161178506025,
        "val_acc": 0.9224691358024691,
        "val_f1": 0.9208854676805693,
        "lr": 0.001
      },
      {
        "epoch": 29,
        "train_loss": 0.22075072952858196,
        "val_loss": 0.24817411129912417,
        "val_acc": 0.9249382716049382,
        "val_f1": 0.9230779218845001,
        "lr": 0.001
      },
      {
        "epoch": 30,
        "train_loss": 0.2022585943949924,
        "val_loss": 0.25004124871311906,
        "val_acc": 0.9232098765432099,
        "val_f1": 0.9212209812651636,
        "lr": 0.0005
      },
      {
        "epoch": 31,
        "train_loss": 0.15590715931947918,
        "val_loss": 0.19194479491198677,
        "val_acc": 0.9409876543209876,
        "val_f1": 0.939485308972657,
        "lr": 0.0005
      },
      {
        "epoch": 32,
        "train_loss": 0.14122061018547194,
        "val_loss": 0.1897640730579461,
        "val_acc": 0.9392592592592592,
        "val_f1": 0.9373480856191595,
        "lr": 0.0005
      },
      {
        "epoch": 33,
        "train_loss": 0.141502788688577,
        "val_loss": 0.1871298411805454,
        "val_acc": 0.9382716049382716,
        "val_f1": 0.9366743257744264,
        "lr": 0.0005
      },
      {
        "epoch": 34,
        "train_loss": 0.13289351079951972,
        "val_loss": 0.19745170557823838,
        "val_acc": 0.94,
        "val_f1": 0.9386123541729571,
        "lr": 0.0005
      },
      {
        "epoch": 35,
        "train_loss": 0.13531270204766893,
        "val_loss": 0.19960624234087887,
        "val_acc": 0.9350617283950617,
        "val_f1": 0.9337095748330034,
        "lr": 0.0005
      },
      {
        "epoch": 36,
        "train_loss": 0.13556913577116492,
        "val_loss": 0.20661196232714876,
        "val_acc": 0.9340740740740741,
        "val_f1": 0.9324557242961478,
        "lr": 0.0005
      },
      {
        "epoch": 37,
        "train_loss": 0.12560709942056003,
        "val_loss": 0.20113951787479747,
        "val_acc": 0.9387654320987654,
        "val_f1": 0.9370941529630337,
        "lr": 0.0005
      },
      {
        "epoch": 38,
        "train_loss": 0.11867540200819811,
        "val_loss": 0.18439324423290357,
        "val_acc": 0.9422222222222222,
        "val_f1": 0.9405729932263052,
        "lr": 0.0005
      },
      {
        "epoch": 39,
        "train_loss": 0.11786406987338387,
        "val_loss": 0.21515363204691212,
        "val_acc": 0.9308641975308642,
        "val_f1": 0.9289085637688211,
        "lr": 0.0005
      },
      {
        "epoch": 40,
        "train_loss": 0.11607623146561885,
        "val_loss": 0.18169023462627276,
        "val_acc": 0.9397530864197531,
        "val_f1": 0.9383896033440055,
        "lr": 0.0005
      },
      {
        "epoch": 41,
        "train_loss": 0.11577095033547692,
        "val_loss": 0.19394382038331726,
        "val_acc": 0.9439506172839506,
        "val_f1": 0.9421635010321768,
        "lr": 0.0005
      },
      {
        "epoch": 42,
        "train_loss": 0.11199281020251385,
        "val_loss": 0.19219226438113363,
        "val_acc": 0.9417283950617283,
        "val_f1": 0.9405044595297565,
        "lr": 0.0005
      },
      {
        "epoch": 43,
        "train_loss": 0.11283316742152368,
        "val_loss": 0.19450849583254454,
        "val_acc": 0.9434567901234568,
        "val_f1": 0.9424361575535567,
        "lr": 0.0005
      },
      {
        "epoch": 44,
        "train_loss": 0.11034162976125464,
        "val_loss": 0.18369301572664967,
        "val_acc": 0.9449382716049383,
        "val_f1": 0.9434950850960229,
        "lr": 0.0005
      },
      {
        "epoch": 45,
        "train_loss": 0.11107758415033926,
        "val_loss": 0.2200454375070609,
        "val_acc": 0.9325925925925926,
        "val_f1": 0.930506941371614,
        "lr": 0.0005
      },
      {
        "epoch": 46,
        "train_loss": 0.10742603752244341,
        "val_loss": 0.23855987263159906,
        "val_acc": 0.9367901234567901,
        "val_f1": 0.935508772448105,
        "lr": 0.00025
      },
      {
        "epoch": 47,
        "train_loss": 0.07689302576904,
        "val_loss": 0.17399533095073727,
        "val_acc": 0.9493827160493827,
        "val_f1": 0.9479891345770728,
        "lr": 0.00025
      },
      {
        "epoch": 48,
        "train_loss": 0.07416650441190158,
        "val_loss": 0.18975268038400103,
        "val_acc": 0.9451851851851852,
        "val_f1": 0.9438583921561822,
        "lr": 0.00025
      },
      {
        "epoch": 49,
        "train_loss": 0.07526854212685063,
        "val_loss": 0.19917785090310072,
        "val_acc": 0.9434567901234568,
        "val_f1": 0.941876539195144,
        "lr": 0.00025
      },
      {
        "epoch": 50,
        "train_loss": 0.07337026934217189,
        "val_loss": 0.17263172961874151,
        "val_acc": 0.9530864197530864,
        "val_f1": 0.9518129996269049,
        "lr": 0.00025
      }
    ]
  }
}
python run.py --run-baseline --config configs/experiment.defaults.json --defaults configs/experiment.defaults.json --splits-output /kaggle/working/artifacts/splits --reports-output /kaggle/working/artifacts/reports/baseline_flips_low_lr.json --checkpoints-output /kaggle/working/checkpoints/baseline_cnn/baseline_flips_low_lr --dataset-root /kaggle/input/datasets/apollo2506/eurosat-dataset/EuroSAT --model-name baseline_cnn --experiment-name baseline_flips_low_lr --seed 42 --train-ratio 0.7 --validation-ratio 0.15 --test-ratio 0.15 --stratified --epochs 50 --batch-size 16 --learning-rate 0.0005 --early-stopping-patience 10 --early-stopping-min-delta 0.0 --scheduler-factor 0.5 --scheduler-patience 5 --min-learning-rate 0.000001 --augmentation-mode flips

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:315.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

{
  "accuracy": 0.9619753086419753,
  "macro_f1_score": 0.9608631195224152,
  "precision": {
    "AnnualCrop": 0.9683257918552036,
    "Forest": 0.9977324263038548,
    "HerbaceousVegetation": 0.9361233480176211,
    "Highway": 0.9699453551912568,
    "Industrial": 0.9564102564102565,
    "Pasture": 0.9423076923076923,
    "PermanentCrop": 0.9076517150395779,
    "Residential": 0.9910514541387024,
    "River": 0.9456521739130435,
    "SeaLake": 0.9889135254988913
  },
  "recall": {
    "AnnualCrop": 0.9511111111111111,
    "Forest": 0.9777777777777777,
    "HerbaceousVegetation": 0.9444444444444444,
    "Highway": 0.9466666666666667,
    "Industrial": 0.9946666666666667,
    "Pasture": 0.98,
    "PermanentCrop": 0.9173333333333333,
    "Residential": 0.9844444444444445,
    "River": 0.928,
    "SeaLake": 0.9911111111111112
  },
  "confusion_matrix": [
    [
      428,
      0,
      1,
      0,
      0,
      4,
      8,
      0,
      6,
      3
    ],
    [
      1,
      440,
      4,
      0,
      0,
      5,
      0,
      0,
      0,
      0
    ],
    [
      1,
      0,
      425,
      1,
      1,
      2,
      18,
      1,
      1,
      0
    ],
    [
      1,
      0,
      1,
      355,
      5,
      0,
      1,
      2,
      9,
      1
    ],
    [
      0,
      0,
      0,
      0,
      373,
      0,
      1,
      1,
      0,
      0
    ],
    [
      2,
      1,
      0,
      1,
      0,
      294,
      2,
      0,
      0,
      0
    ],
    [
      4,
      0,
      17,
      0,
      5,
      4,
      344,
      0,
      1,
      0
    ],
    [
      0,
      0,
      1,
      1,
      4,
      0,
      1,
      443,
      0,
      0
    ],
    [
      4,
      0,
      5,
      8,
      2,
      3,
      4,
      0,
      348,
      1
    ],
    [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      3,
      446
    ]
  ],
  "checkpoint_path": "/kaggle/working/checkpoints/baseline_cnn/baseline_flips_low_lr/best_checkpoint.pt",
  "report_path": "/kaggle/working/artifacts/reports/baseline_flips_low_lr.json",
  "training_state": {
    "epochs_requested": 50,
    "epochs_ran": 50,
    "best_validation_loss": 0.12996174572653374,
    "best_validation_f1": 0.9597807253474178,
    "best_epoch": 46,
    "early_stopping_patience": 10,
    "early_stopping_min_delta": 0.0,
    "learning_rate": 0.0005,
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "min_learning_rate": 1e-06,
    "batch_size": 16,
    "class_weights": [
      0.8999999761581421,
      0.8999999761581421,
      0.8999999761581421,
      1.0800000429153442,
      1.0800000429153442,
      1.350000023841858,
      1.0800000429153442,
      0.8999999761581421,
      1.0800000429153442,
      0.8999999761581421
    ],
    "epoch_logs": [
      {
        "epoch": 1,
        "train_loss": 1.2904232855123514,
        "val_loss": 0.9487888274465021,
        "val_acc": 0.6481481481481481,
        "val_f1": 0.6360212444817843,
        "lr": 0.0005
      },
      {
        "epoch": 2,
        "train_loss": 0.8382649324998235,
        "val_loss": 0.6947769108118387,
        "val_acc": 0.7459259259259259,
        "val_f1": 0.7385206293837422,
        "lr": 0.0005
      },
      {
        "epoch": 3,
        "train_loss": 0.7271218874354652,
        "val_loss": 0.575508244086321,
        "val_acc": 0.7933333333333333,
        "val_f1": 0.7854677958048699,
        "lr": 0.0005
      },
      {
        "epoch": 4,
        "train_loss": 0.6724758685744555,
        "val_loss": 0.5372832265103192,
        "val_acc": 0.8024691358024691,
        "val_f1": 0.7958222262944118,
        "lr": 0.0005
      },
      {
        "epoch": 5,
        "train_loss": 0.6133706836682286,
        "val_loss": 0.53988769675759,
        "val_acc": 0.8074074074074075,
        "val_f1": 0.802199123974139,
        "lr": 0.0005
      },
      {
        "epoch": 6,
        "train_loss": 0.5612256090123642,
        "val_loss": 0.4631315743450743,
        "val_acc": 0.8417283950617284,
        "val_f1": 0.8358016747568072,
        "lr": 0.0005
      },
      {
        "epoch": 7,
        "train_loss": 0.51846501314398,
        "val_loss": 0.3950229260390331,
        "val_acc": 0.86,
        "val_f1": 0.8558120562203472,
        "lr": 0.0005
      },
      {
        "epoch": 8,
        "train_loss": 0.4927037771658849,
        "val_loss": 0.4073514863476259,
        "val_acc": 0.8555555555555555,
        "val_f1": 0.8503305787087928,
        "lr": 0.0005
      },
      {
        "epoch": 9,
        "train_loss": 0.45367420839174144,
        "val_loss": 0.45172670760052647,
        "val_acc": 0.8328395061728395,
        "val_f1": 0.8309525760262846,
        "lr": 0.0005
      },
      {
        "epoch": 10,
        "train_loss": 0.425406731699803,
        "val_loss": 0.3224052839828142,
        "val_acc": 0.8888888888888888,
        "val_f1": 0.885022701942391,
        "lr": 0.0005
      },
      {
        "epoch": 11,
        "train_loss": 0.3910324041670198,
        "val_loss": 0.31509362795073026,
        "val_acc": 0.8920987654320988,
        "val_f1": 0.8873610063276913,
        "lr": 0.0005
      },
      {
        "epoch": 12,
        "train_loss": 0.3687532049116825,
        "val_loss": 0.33648474287634944,
        "val_acc": 0.874320987654321,
        "val_f1": 0.8732216019984635,
        "lr": 0.0005
      },
      {
        "epoch": 13,
        "train_loss": 0.3393864758114146,
        "val_loss": 0.32351444527622214,
        "val_acc": 0.8837037037037037,
        "val_f1": 0.8817883558429971,
        "lr": 0.0005
      },
      {
        "epoch": 14,
        "train_loss": 0.32584802703474935,
        "val_loss": 0.34581463611189744,
        "val_acc": 0.8819753086419753,
        "val_f1": 0.8786965806630518,
        "lr": 0.0005
      },
      {
        "epoch": 15,
        "train_loss": 0.3208275660147572,
        "val_loss": 0.3266542336921158,
        "val_acc": 0.8864197530864197,
        "val_f1": 0.8845032477022212,
        "lr": 0.0005
      },
      {
        "epoch": 16,
        "train_loss": 0.2847947519471122,
        "val_loss": 0.2658508061147758,
        "val_acc": 0.902962962962963,
        "val_f1": 0.900699636396188,
        "lr": 0.0005
      },
      {
        "epoch": 17,
        "train_loss": 0.2805991787613132,
        "val_loss": 0.21091157750890668,
        "val_acc": 0.9298765432098766,
        "val_f1": 0.9273247144756706,
        "lr": 0.0005
      },
      {
        "epoch": 18,
        "train_loss": 0.2618938682217926,
        "val_loss": 0.2376801993235085,
        "val_acc": 0.9177777777777778,
        "val_f1": 0.915180514549977,
        "lr": 0.0005
      },
      {
        "epoch": 19,
        "train_loss": 0.25711982044574133,
        "val_loss": 0.2131790116213743,
        "val_acc": 0.9239506172839507,
        "val_f1": 0.9218362955731063,
        "lr": 0.0005
      },
      {
        "epoch": 20,
        "train_loss": 0.24026705079251828,
        "val_loss": 0.22554804875337112,
        "val_acc": 0.9244444444444444,
        "val_f1": 0.921850649909193,
        "lr": 0.0005
      },
      {
        "epoch": 21,
        "train_loss": 0.24157092605351885,
        "val_loss": 0.24607277740611377,
        "val_acc": 0.9096296296296297,
        "val_f1": 0.9072469514458573,
        "lr": 0.0005
      },
      {
        "epoch": 22,
        "train_loss": 0.2232716625584715,
        "val_loss": 0.20627946055108043,
        "val_acc": 0.9281481481481482,
        "val_f1": 0.9263246166817876,
        "lr": 0.0005
      },
      {
        "epoch": 23,
        "train_loss": 0.21913627671434777,
        "val_loss": 0.19726936865183634,
        "val_acc": 0.9301234567901234,
        "val_f1": 0.9284585141187147,
        "lr": 0.0005
      },
      {
        "epoch": 24,
        "train_loss": 0.21470718716811735,
        "val_loss": 0.20548059464446966,
        "val_acc": 0.9249382716049382,
        "val_f1": 0.921988985949335,
        "lr": 0.0005
      },
      {
        "epoch": 25,
        "train_loss": 0.20164108423826596,
        "val_loss": 0.18734311191257988,
        "val_acc": 0.9298765432098766,
        "val_f1": 0.9283212570823798,
        "lr": 0.0005
      },
      {
        "epoch": 26,
        "train_loss": 0.18491926946631568,
        "val_loss": 0.2601291373276173,
        "val_acc": 0.9046913580246914,
        "val_f1": 0.9020680998782936,
        "lr": 0.0005
      },
      {
        "epoch": 27,
        "train_loss": 0.1922849867524037,
        "val_loss": 0.18939838352841568,
        "val_acc": 0.9353086419753086,
        "val_f1": 0.9327352103933082,
        "lr": 0.0005
      },
      {
        "epoch": 28,
        "train_loss": 0.19144495937251527,
        "val_loss": 0.19322689282353167,
        "val_acc": 0.9348148148148148,
        "val_f1": 0.9332442213872705,
        "lr": 0.0005
      },
      {
        "epoch": 29,
        "train_loss": 0.1819283676059135,
        "val_loss": 0.21189195118478077,
        "val_acc": 0.9212345679012346,
        "val_f1": 0.9182132191680316,
        "lr": 0.0005
      },
      {
        "epoch": 30,
        "train_loss": 0.17759746182182026,
        "val_loss": 0.18309032705689796,
        "val_acc": 0.934320987654321,
        "val_f1": 0.9330583979794278,
        "lr": 0.0005
      },
      {
        "epoch": 31,
        "train_loss": 0.168995469190553,
        "val_loss": 0.1953656758959419,
        "val_acc": 0.9328395061728395,
        "val_f1": 0.930588903347606,
        "lr": 0.0005
      },
      {
        "epoch": 32,
        "train_loss": 0.1636862968664511,
        "val_loss": 0.18514944330741484,
        "val_acc": 0.934320987654321,
        "val_f1": 0.9322152964280498,
        "lr": 0.0005
      },
      {
        "epoch": 33,
        "train_loss": 0.16080116850901915,
        "val_loss": 0.197636350080018,
        "val_acc": 0.9340740740740741,
        "val_f1": 0.9323970314331989,
        "lr": 0.0005
      },
      {
        "epoch": 34,
        "train_loss": 0.16051633437613244,
        "val_loss": 0.26156061751102044,
        "val_acc": 0.914074074074074,
        "val_f1": 0.9139432462551429,
        "lr": 0.0005
      },
      {
        "epoch": 35,
        "train_loss": 0.1541679698485186,
        "val_loss": 0.19195689520187098,
        "val_acc": 0.9320987654320988,
        "val_f1": 0.9297458972962381,
        "lr": 0.0005
      },
      {
        "epoch": 36,
        "train_loss": 0.1444115033809548,
        "val_loss": 0.1958126267663811,
        "val_acc": 0.9323456790123457,
        "val_f1": 0.9299301829864992,
        "lr": 0.00025
      },
      {
        "epoch": 37,
        "train_loss": 0.10567611642861455,
        "val_loss": 0.1400328985696612,
        "val_acc": 0.9523456790123457,
        "val_f1": 0.9507543415638094,
        "lr": 0.00025
      },
      {
        "epoch": 38,
        "train_loss": 0.09919214736762412,
        "val_loss": 0.1721133561742684,
        "val_acc": 0.9446913580246914,
        "val_f1": 0.9434597089723263,
        "lr": 0.00025
      },
      {
        "epoch": 39,
        "train_loss": 0.09748586206900925,
        "val_loss": 0.14963728900959822,
        "val_acc": 0.9518518518518518,
        "val_f1": 0.9503735940459617,
        "lr": 0.00025
      },
      {
        "epoch": 40,
        "train_loss": 0.08979124171914588,
        "val_loss": 0.14428237926141912,
        "val_acc": 0.9525925925925925,
        "val_f1": 0.9513424269004217,
        "lr": 0.00025
      },
      {
        "epoch": 41,
        "train_loss": 0.09390758246159094,
        "val_loss": 0.15512187219501644,
        "val_acc": 0.9493827160493827,
        "val_f1": 0.9478031748434507,
        "lr": 0.00025
      },
      {
        "epoch": 42,
        "train_loss": 0.09382260978239523,
        "val_loss": 0.14014672195257952,
        "val_acc": 0.9543209876543209,
        "val_f1": 0.9533940249355926,
        "lr": 0.00025
      },
      {
        "epoch": 43,
        "train_loss": 0.08659636525225925,
        "val_loss": 0.1547651955409127,
        "val_acc": 0.9525925925925925,
        "val_f1": 0.9515012406056329,
        "lr": 0.000125
      },
      {
        "epoch": 44,
        "train_loss": 0.06626038559361697,
        "val_loss": 0.13006632489915018,
        "val_acc": 0.9604938271604938,
        "val_f1": 0.9591623031911947,
        "lr": 0.000125
      },
      {
        "epoch": 45,
        "train_loss": 0.06268122619323623,
        "val_loss": 0.13857863922235478,
        "val_acc": 0.9565432098765432,
        "val_f1": 0.9550333093823994,
        "lr": 0.000125
      },
      {
        "epoch": 46,
        "train_loss": 0.061371935097869625,
        "val_loss": 0.12996174572653374,
        "val_acc": 0.9612345679012345,
        "val_f1": 0.9597807253474178,
        "lr": 0.000125
      },
      {
        "epoch": 47,
        "train_loss": 0.05791981401711068,
        "val_loss": 0.14357038518720244,
        "val_acc": 0.957037037037037,
        "val_f1": 0.9556026466382,
        "lr": 0.000125
      },
      {
        "epoch": 48,
        "train_loss": 0.05899327019140989,
        "val_loss": 0.15305212663322418,
        "val_acc": 0.9535802469135802,
        "val_f1": 0.9529027164344888,
        "lr": 0.000125
      },
      {
        "epoch": 49,
        "train_loss": 0.05816967682349459,
        "val_loss": 0.15519519321400022,
        "val_acc": 0.9538271604938272,
        "val_f1": 0.9527272309060686,
        "lr": 0.000125
      },
      {
        "epoch": 50,
        "train_loss": 0.055186810365978334,
        "val_loss": 0.12808062396391767,
        "val_acc": 0.9590123456790124,
        "val_f1": 0.9574669310406794,
        "lr": 0.000125
      }
    ]
  }
}
Saved summary CSV: /kaggle/working/artifacts/reports/baseline_experiment_summary.csv

,run_id,augmentation_mode,learning_rate,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path
0,baseline_flips_low_lr,flips,0.0005,50,50,0.959781,0.961975,0.960863,/kaggle/working/artifacts/reports/baseline_fli...,/kaggle/working/checkpoints/baseline_cnn/basel...
1,baseline_flips,flips,0.0010,50,50,0.951813,0.947901,0.946238,/kaggle/working/artifacts/reports/baseline_fli...,/kaggle/working/checkpoints/baseline_cnn/basel...
2,baseline_reference_none,none,0.0010,50,50,0.915363,0.912346,0.908949,/kaggle/working/artifacts/reports/baseline_ref...,/kaggle/working/checkpoints/baseline_cnn/basel...

In [6]:
best_baseline = baseline_summary.iloc[0]
print('Best baseline configuration:')
print(best_baseline[['run_id', 'augmentation_mode', 'learning_rate', 'test_accuracy', 'test_macro_f1']])

baseline_summary

Best baseline configuration:
run_id               baseline_flips_low_lr
augmentation_mode                    flips
learning_rate                       0.0005
test_accuracy                     0.961975
test_macro_f1                     0.960863
Name: 0, dtype: object

,run_id,augmentation_mode,learning_rate,epochs_requested,epochs_ran,val_f1_best,test_accuracy,test_macro_f1,report_path,checkpoint_path
0,baseline_flips_low_lr,flips,0.0005,50,50,0.959781,0.961975,0.960863,/kaggle/working/artifacts/reports/baseline_fli...,/kaggle/working/checkpoints/baseline_cnn/basel...
1,baseline_flips,flips,0.0010,50,50,0.951813,0.947901,0.946238,/kaggle/working/artifacts/reports/baseline_fli...,/kaggle/working/checkpoints/baseline_cnn/basel...
2,baseline_reference_none,none,0.0010,50,50,0.915363,0.912346,0.908949,/kaggle/working/artifacts/reports/baseline_ref...,/kaggle/working/checkpoints/baseline_cnn/basel...

In [7]:
!zip -r /kaggle/working/baseline_results.zip /kaggle/working/artifacts /kaggle/working/checkpoints

  adding: kaggle/working/artifacts/ (stored 0%)
  adding: kaggle/working/artifacts/reports/ (stored 0%)
  adding: kaggle/working/artifacts/reports/baseline_flips.json (deflated 78%)
  adding: kaggle/working/artifacts/reports/baseline_flips_low_lr.training_log.tmp.json (deflated 78%)
  adding: kaggle/working/artifacts/reports/baseline_reference_none.json (deflated 79%)
  adding: kaggle/working/artifacts/reports/baseline_flips_low_lr.json (deflated 79%)
  adding: kaggle/working/artifacts/reports/baseline_reference_none.training_log.tmp.json (deflated 78%)
  adding: kaggle/working/artifacts/reports/baseline_flips.training_log.tmp.json (deflated 77%)
  adding: kaggle/working/artifacts/reports/baseline_experiment_summary.csv (deflated 63%)
  adding: kaggle/working/artifacts/splits/ (stored 0%)
  adding: kaggle/working/artifacts/splits/split_manifest.json (deflated 33%)
  adding: kaggle/working/artifacts/splits/test_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/validation_split.json (deflated 98%)
  adding: kaggle/working/artifacts/splits/train_split.json (deflated 98%)
  adding: kaggle/working/checkpoints/ (stored 0%)
  adding: kaggle/working/checkpoints/baseline_cnn/ (stored 0%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_reference_none/ (stored 0%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_reference_none/best_checkpoint.pt (deflated 6%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_reference_none/best_checkpoint.metadata.json (deflated 78%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips/ (stored 0%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips/best_checkpoint.pt (deflated 6%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips/best_checkpoint.metadata.json (deflated 78%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips_low_lr/ (stored 0%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips_low_lr/best_checkpoint.pt (deflated 7%)
  adding: kaggle/working/checkpoints/baseline_cnn/baseline_flips_low_lr/best_checkpoint.metadata.json (deflated 78%)